export const bazaDateMasini= {
    Bmw: {
        "2005 BMW Seria 3(E9X)": {
            "Sedan 4-door(E90)": {
                "318i 2.0L 129hp": {
                    imagine: '/bmwE90sedan.jpg',
                    'Anii de fabricatie': "2005-2007",
                    'Numarul de scaune':5,
                    'Numarul de usi':4,

                    'Consumul urban (l/100km)':9.5,
                    'Consumul pe autostrada (l/100km)':5.9,
                    'Consumul mixt (l/100km)':7.3,
                    'Tipul Carburantului': "Benzina",
                    'Acceleratie (0-100km/h) (secunde)':10,
                    'Viteza maxima (km/h)':208,
                    'Standard ecologic':"Euro 4",
                    'Raport putere/greutate (CP/tona)':97.4,
                    'Raport cuplu/greutate (Nm/tona)':135.8,

                    'Capacitate cilindrica(cc)': 1991,
                    'Putere(hp)': 129,
                    'Cuplu(Nm)': 180,
                    'Codul Motor': "N46B20B",
                    'Configuratia Motorului': "4 cilindrii in linie, 4 valve per cilindru",
                    'Tipul de asiratie': "Aspirat Natural",
                    'Capacitate baie ulei(l)':4.25,
                    'Cantitatea lichidului de racire(l)':7.2,

                    'Masa proprie(kg)':1325,
                    'Masa maxima autorizata(kg)':1840,
                    'Volumul minim al portbagajului(l)':460,
                    'Volumul rezervorului(l)':60,

                    'Lungime(mm)':4520 ,
                    'Latime(mm)':1817,
                    'Inaltime(mm)':1421,

                    'Tractiune':"Spate",
                    'Tipul cutiei de viteze':"Cutie de viteze manuala - 6 trepte",
                    'Suspensie fata':"Amortizor cu arc",
                    'Suspensie spate':"Arc elicoidal",
                    'Frane fata':"Discuri ventilate",
                    'Frane spate':"Disc",
                },

                "318d 2.0L 122hp": {
                    imagine: '/bmwE90sedan.jpg',
                    "Anii de fabricatie": "2006-2007",
                    'Numarul de scaune': 5,
                    'Numarul de usi': 4,

                    'Consumul urban (l/100km)': 7.6,
                    'Consumul pe autostrada (l/100km)': 4.4,
                    'Consumul mixt (l/100km)': 5.7,
                    'Tipul Carburantului': "Diesel",
                    'Acceleratie (0-100km/h) (secunde)': 10.6,
                    'Viteza maxima (km/h)': 206,
                    'Standard ecologic': "Euro 4",
                    'Raport putere/greutate (CP/tona)': 85,
                    'Raport cuplu/greutate (Nm/tona)': 195.1,

                    'Capacitate cilindrica(cc)': 1995,
                    'Putere(hp)': 122 ,
                    'Cuplu(Nm)': 280,
                    'Codul Motor': "M47D20TU2",
                    'Configuratia Motorului': "4 cilindrii in linie, 4 valve per cilindru",
                    'Tipul de asiratie': "Turbosuflanta",
                    'Capacitate baie ulei(l)': 5.2,
                    'Cantitatea lichidului de racire(l)': 7.8,

                    'Masa proprie(kg)': 1435 ,
                    'Masa maxima autorizata(kg)': 1950 ,
                    'Volumul minim al portbagajului(l)': 460 ,
                    'Volumul rezervorului(l)': 61 ,

                    'Lungime(mm)': 4520,
                    'Latime(mm)': 1817 ,
                    'Inaltime(mm)': 1421 ,

                    'Tractiune': "Spate",
                    'Tipul cutiei de viteze': "Cutie de viteze manuala - 6 trepte",
                    'Suspensie fata': "Independent, tip McPherson cu arcuri elicoidale și bară stabilizatoare",
                    'Suspensie spate': "Arc elicoidal",
                    'Frane fata': "Disc",
                    'Frane spate': "Disc",
                },

                "320d 2.0L 163hp": {
                    imagine: '/bmwE90sedan.jpg',
                    "Anii de fabricatie": "2005-2007",
                    'Numarul de scaune': 5,
                    'Numarul de usi': 4,
                    'Consumul urban (l/100km)': 6.5,
                    'Consumul pe autostrada (l/100km)': 4.5,
                    'Consumul mixt (l/100km)': 5.3,
                    'Tipul Carburantului': "Diesel",
                    'Acceleratie (0-100km/h) (secunde)': 8.3,
                    'Viteza maxima (km/h)': 225,
                    'Standard ecologic': "Euro 4",
                    'Raport putere/greutate (CP/tona)': 113.6,
                    'Raport cuplu/greutate (Nm/tona)': 236.9,
                    'Capacitate cilindrica(cc)': 1995,
                    'Putere(hp)': 163,
                    'Cuplu(Nm)': 340,
                    'Codul Motor': "M47D20TU2",
                    'Configuratia Motorului': "4 cilindrii in linie, 4 valve per cilindru",
                    'Tipul de asiratie': "Turbosuflanta",
                    'Capacitate baie ulei(l)': 5.2,
                    'Cantitatea lichidului de racire(l)': 7.5,
                    'Masa proprie(kg)': 1435,
                    'Masa maxima autorizata(kg)': 1950,
                    'Volumul minim al portbagajului(l)': 460,
                    'Volumul rezervorului(l)': 61,
                    'Lungime(mm)': 4520,
                    'Latime(mm)': 1817,
                    'Inaltime(mm)': 1421,
                    'Tractiune': "Spate",
                    'Tipul cutiei de viteze': "Cutie de viteze manuala - 6 trepte",
                    'Suspensie fata': "Independent, tip McPherson cu arcuri elicoidale și bară stabilizatoare",
                    'Suspensie spate': "Arc elicoidal",
                    'Frane fata': "Disc",
                    'Frane spate': "Disc",
                },

                "320i 2.0L 150hp": {
                    imagine: '/bmwE90sedan.jpg',
                    "Anii de fabricatie": "2005-2007",
                    'Numarul de scaune': 5,
                    'Numarul de usi': 4,
                    'Consumul urban (l/100km)': 10.7,
                    'Consumul pe autostrada (l/100km)': 5.6,
                    'Consumul mixt (l/100km)': 7.4,
                    'Tipul Carburantului': "Benzina",
                    'Acceleratie (0-100km/h) (secunde)': 8.5,
                    'Viteza maxima (km/h)': 220,
                    'Standard ecologic': "Euro 4",
                    'Raport putere/greutate (CP/tona)': 107.5,
                    'Raport cuplu/greutate (Nm/tona)': 143.4,
                    'Capacitate cilindrica(cc)': 1995,
                    'Putere(hp)': 150,
                    'Cuplu(Nm)': 200,
                    'Codul Motor': "N46B20B",
                    'Configuratia Motorului': "4 cilindrii in linie, 4 valve per cilindru",
                    'Tipul de asiratie': "Aspirat Natural",
                    'Capacitate baie ulei(l)': 4.25,
                    'Cantitatea lichidului de racire(l)': 7.2,
                    'Masa proprie(kg)': 1395,
                    'Masa maxima autorizata(kg)': 1840,
                    'Volumul minim al portbagajului(l)': 460,
                    'Volumul rezervorului(l)': 60,
                    'Lungime(mm)': 4520,
                    'Latime(mm)': 1817,
                    'Inaltime(mm)': 1421,
                    'Tractiune': "Spate",
                    'Tipul cutiei de viteze': "Cutie de viteze manuala - 6 trepte",
                    'Suspensie fata': "Amortizor cu arc",
                    'Suspensie spate': "Arc elicoidal",
                    'Frane fata': "Discuri ventilate",
                    'Frane spate': "Disc",
                },


                "325d 3.0L 197hp": {
                    imagine: '/bmwE90sedan.jpg',
                    "Anii de fabricatie": "2006-2008",
                    'Numarul de scaune': 5,
                    'Numarul de usi': 4,
                    'Consumul urban (l/100km)': 8.6,
                    'Consumul pe autostrada (l/100km)': 5.1,
                    'Consumul mixt (l/100km)': 6.4,
                    'Tipul Carburantului': "Diesel",
                    'Acceleratie (0-100km/h) (secunde)': 7.4,
                    'Viteza maxima (km/h)': 235,
                    'Standard ecologic': "Euro 4",
                    'Raport putere/greutate (CP/tona)': 131.3,
                    'Raport cuplu/greutate (Nm/tona)': 266.7,
                    'Capacitate cilindrica(cc)': 2993,
                    'Putere(hp)': 197,
                    'Cuplu(Nm)': 400,
                    'Codul Motor': "M57D30TU2",
                    'Configuratia Motorului': "6 cilindrii in linie, 4 valve per cilindru",
                    'Tipul de asiratie': "Turbosuflanta",
                    'Capacitate baie ulei(l)': 7.5,
                    'Cantitatea lichidului de racire(l)': 7.9,
                    'Masa proprie(kg)': 1500,
                    'Masa maxima autorizata(kg)': 2045,
                    'Volumul minim al portbagajului(l)': 460,
                    'Volumul rezervorului(l)': 61,
                    'Lungime(mm)': 4520,
                    'Latime(mm)': 1820,
                    'Inaltime(mm)': 1420,
                    'Tractiune': "Spate",
                    'Tipul cutiei de viteze': "Cutie de viteze manuala - 6 trepte",
                    'Suspensie fata': "Independent de tip McPherson",
                    'Suspensie spate': "Suspensie multi-link independentă",
                    'Frane fata': "Discuri ventilate",
                    'Frane spate': "Disc",
                },

                "325i 2.5L 218hp": {
                    imagine: '/bmwE90sedan.jpg',
                    "Anii de fabricatie": "2005-2007",
                    'Numarul de scaune': 5,
                    'Numarul de usi': 4,
                    'Consumul urban (l/100km)': 12.1,
                    'Consumul pe autostrada (l/100km)': 6.2,
                    'Consumul mixt (l/100km)': 8.4,
                    'Tipul Carburantului': "Benzina",
                    'Acceleratie (0-100km/h) (secunde)': 7,
                    'Viteza maxima (km/h)': 245,
                    'Standard ecologic': "Euro 4",
                    'Raport putere/greutate (CP/tona)': 146.3,
                    'Raport cuplu/greutate (Nm/tona)': 167.8,
                    'Capacitate cilindrica(cc)': 2497,
                    'Putere(hp)': 218,
                    'Cuplu(Nm)': 250,
                    'Codul Motor': "N52B25A",
                    'Configuratia Motorului': "6 cilindrii in linie, 4 valve per cilindru",
                    'Tipul de asiratie': "Aspirat Natural",
                    'Capacitate baie ulei(l)': 6.5,
                    'Cantitatea lichidului de racire(l)': 8.2,
                    'Masa proprie(kg)': 1490,
                    'Masa maxima autorizata(kg)': 1935,
                    'Volumul minim al portbagajului(l)': 460,
                    'Volumul rezervorului(l)': 60,
                    'Lungime(mm)': 4520,
                    'Latime(mm)': 1820,
                    'Inaltime(mm)': 1420,
                    'Tractiune': "Spate",
                    'Tipul cutiei de viteze': "Cutie de viteze manuala - 6 trepte",
                    'Suspensie fata': "Amortizor cu arc",
                    'Suspensie spate': "Arc elicoidal",
                    'Frane fata': "Discuri ventilate",
                    'Frane spate': "Disc",
                },



                "330i 3.0L 258hp": {
                    imagine: '/bmwE90sedan.jpg',
                    "Anii de fabricatie": "2005-2007",
                    'Numarul de scaune': 5,
                    'Numarul de usi': 4,
                    'Consumul urban (l/100km)': 12.7,
                    'Consumul pe autostrada (l/100km)': 6.4,
                    'Consumul mixt (l/100km)': 8.7,
                    'Tipul Carburantului': "Benzina",
                    'Acceleratie (0-100km/h) (secunde)': 6.3,
                    'Viteza maxima (km/h)': 250,
                    'Standard ecologic': "Euro 4",
                    'Raport putere/greutate (CP/tona)': 169.2,
                    'Raport cuplu/greutate (Nm/tona)': 196.7,
                    'Capacitate cilindrica(cc)': 2996,
                    'Putere(hp)': 258,
                    'Cuplu(Nm)': 300,
                    'Codul Motor': "N52B30A",
                    'Configuratia Motorului': "6 cilindrii in linie, 4 valve per cilindru",
                    'Tipul de asiratie': "Aspirat Natural",
                    'Capacitate baie ulei(l)': 6.5,
                    'Cantitatea lichidului de racire(l)': 8.2,
                    'Masa proprie(kg)': 1525,
                    'Masa maxima autorizata(kg)': 1970,
                    'Volumul minim al portbagajului(l)': 460,
                    'Volumul rezervorului(l)': 60,
                    'Lungime(mm)': 4520,
                    'Latime(mm)': 1820,
                    'Inaltime(mm)': 1420,
                    'Tractiune': "Spate",
                    'Tipul cutiei de viteze': "Cutie de viteze manuala - 6 trepte",
                    'Suspensie fata': "Amortizor cu arc",
                    'Suspensie spate': "Arc elicoidal",
                    'Frane fata': "Discuri ventilate",
                    'Frane spate': "Disc",
                },

                "330d 3.0L 231hp": {
                    imagine: '/bmwE90sedan.jpg',
                    "Anii de fabricatie": "2005-2007",
                    'Numarul de scaune': 5,
                    'Numarul de usi': 4,
                    'Consumul urban (l/100km)': 8.8,
                    'Consumul pe autostrada (l/100km)': 5.2,
                    'Consumul mixt (l/100km)': 6.6,
                    'Tipul Carburantului': "Diesel",
                    'Acceleratie (0-100km/h) (secunde)': 6.7,
                    'Viteza maxima (km/h)': 250,
                    'Standard ecologic': "Euro 4",
                    'Raport putere/greutate (CP/tona)': 152.5,
                    'Raport cuplu/greutate (Nm/tona)': 330,
                    'Capacitate cilindrica(cc)': 2993,
                    'Putere(hp)': 231,
                    'Cuplu(Nm)': 500,
                    'Codul Motor': "M57D30TU2",
                    'Configuratia Motorului': "6 cilindrii in linie, 4 valve per cilindru",
                    'Tipul de asiratie': "Aspirat Natural",
                    'Capacitate baie ulei(l)': 7.5,
                    'Cantitatea lichidului de racire(l)': 7.8,
                    'Masa proprie(kg)': 1515,
                    'Masa maxima autorizata(kg)': 2030,
                    'Volumul minim al portbagajului(l)': 460,
                    'Volumul rezervorului(l)': 61,
                    'Lungime(mm)': 4520,
                    'Latime(mm)': 1820,
                    'Inaltime(mm)': 1420,
                    'Tractiune': "Spate",
                    'Tipul cutiei de viteze': "Cutie de viteze manuala - 6 trepte",
                    'Suspensie fata': "Amortizor cu arc",
                    'Suspensie spate': "Arc elicoidal",
                    'Frane fata': "Discuri ventilate",
                    'Frane spate': "Disc",
                },


            },
        },
    },

    Audi: {
        "2007 Audi A4(B8)":{
            "Sedan 4-door":{
                "1.8 TFSI 120hp": {
                    imagine: '/audia4b8sedan.jpg',
                    "Anii de fabricatie": "2007-2011",
                    'Numarul de scaune': 5,
                    'Numarul de usi': 4,
                    'Consumul urban (l/100km)': 9.9,
                    'Consumul pe autostrada (l/100km)': 5.5,
                    'Consumul mixt (l/100km)': 7.1,
                    'Tipul Carburantului': "Benzina",
                    'Acceleratie (0-100km/h) (secunde)': 10.5,
                    'Viteza maxima (km/h)': 208,
                    'Standard ecologic': "Euro 4",
                    'Raport putere/greutate (CP/tona)': 85.1,
                    'Raport cuplu/greutate (Nm/tona)': 163.1,
                    'Capacitate cilindrica(cc)': 1798,
                    'Putere(hp)': 120,
                    'Cuplu(Nm)': 230,
                    'Codul Motor': "EA888 / CDHA",
                    'Configuratia Motorului': "4 cilindrii in linie, 4 valve per cilindru",
                    'Tipul de asiratie': "Turbosuflanta",
                    'Capacitate baie ulei(l)': 4.6,
                    'Cantitatea lichidului de racire(l)': 7,
                    'Masa proprie(kg)': 1410,
                    'Masa maxima autorizata(kg)': 1960,
                    'Volumul minim al portbagajului(l)': 480,
                    'Volumul rezervorului(l)': 65,
                    'Lungime(mm)': 4703,
                    'Latime(mm)': 1826,
                    'Inaltime(mm)': 1427,
                    'Tractiune': "Fata",
                    'Tipul cutiei de viteze': "Cutie de viteze manuala - 6 trepte",
                    'Suspensie fata': "Suspensie multi-link independentă",
                    'Suspensie spate': "Suspensie independentă cu arc multi-legături cu stabilizator",
                    'Frane fata': "Discuri ventilate",
                    'Frane spate': "Disc",
                    'Emisii(g/km)':  169 ,
                },

                "1.8 TFSI 160hp": {
                    imagine: '/audia4b8sedan.jpg',
                    'Anii de fabricatie': "2007-2011",
                    'Numarul de scaune': 5,
                    'Numarul de usi': 4,
                    'Consumul urban (l/100km)': 9.9,
                    'Consumul pe autostrada (l/100km)': 5.5,
                    'Consumul mixt (l/100km)': 7.1,
                    'Tipul Carburantului': "Benzina",
                    'Acceleratie (0-100km/h) (secunde)': 8.6,
                    'Viteza maxima (km/h)': 225,
                    'Standard ecologic': "Euro 4",
                    'Raport putere/greutate (CP/tona)': 113.5,
                    'Raport cuplu/greutate (Nm/tona)': 177.3,
                    'Capacitate cilindrica(cc)': 1798,
                    'Putere(hp)': 160,
                    'Cuplu(Nm)': 250,
                    'Codul Motor': "EA888 / CDHB",
                    'Configuratia Motorului': "4 cilindrii in linie, 4 valve per cilindru",
                    'Tipul de asiratie': "Turbosuflanta",
                    'Capacitate baie ulei(l)': 4.6,
                    'Cantitatea lichidului de racire(l)': 7,
                    'Masa proprie(kg)': 1410,
                    'Masa maxima autorizata(kg)': 1960,
                    'Volumul minim al portbagajului(l)': 480,
                    'Volumul rezervorului(l)': 65,
                    'Lungime(mm)': 4703,
                    'Latime(mm)': 1826,
                    'Inaltime(mm)': 1427,
                    'Tractiune': "Fata",
                    'Tipul cutiei de viteze': "Cutie de viteze manuala - 6 trepte",
                    'Suspensie fata': "Suspensie multi-link independentă",
                    'Suspensie spate': "Suspensie independentă cu arc multi-legături cu stabilizator",
                    'Frane fata': "Discuri ventilate",
                    'Frane spate': "Disc",
                    'Emisii(g/km)':  169 ,
                },


                "2.0 TDI 143hp": {
                    imagine: '/audia4b8sedan.jpg',
                    'Anii de fabricatie': "2007-2011",
                    'Numarul de scaune': 5,
                    'Numarul de usi': 4,
                    'Consumul urban (l/100km)': 7.5,
                    'Consumul pe autostrada (l/100km)': 4.3,
                    'Consumul mixt (l/100km)': 5.5,
                    'Tipul Carburantului': "Diesel",
                    'Acceleratie (0-100km/h) (secunde)': 9.4,
                    'Viteza maxima (km/h)': 215,
                    'Standard ecologic': "Euro 4",
                    'Raport putere/greutate (CP/tona)': 97.9,
                    'Raport cuplu/greutate (Nm/tona)': 219.2,
                    'Capacitate cilindrica(cc)': 1968,
                    'Putere(hp)': 143,
                    'Cuplu(Nm)': 320,
                    'Codul Motor': "EA189 / CAGA",
                    'Configuratia Motorului': "4 cilindrii in linie, 4 valve per cilindru",
                    'Tipul de asiratie': "Turbosuflanta",
                    'Capacitate baie ulei(l)': 5,
                    'Cantitatea lichidului de racire(l)': 7.5,
                    'Masa proprie(kg)': 1460,
                    'Masa maxima autorizata(kg)': 2010,
                    'Volumul minim al portbagajului(l)': 480,
                    'Volumul rezervorului(l)': 70,
                    'Lungime(mm)': 4703,
                    'Latime(mm)': 1826,
                    'Inaltime(mm)': 1427,
                    'Tractiune': "Fata",
                    'Tipul cutiei de viteze': "Cutie de viteze manuala - 6 trepte",
                    'Suspensie fata': "Suspensie multi-link independentă",
                    'Suspensie spate': "Suspensie independentă cu arc multi-legături cu stabilizator",
                    'Frane fata': "Discuri ventilate",
                    'Frane spate': "Disc",
                    'Emisii(g/km)':  144 ,
                },

                "2.0 TDI 170hp": {
                    imagine: '/audia4b8sedan.jpg',
                    'Anii de fabricatie': "2007-2011",
                    'Numarul de scaune': 5,
                    'Numarul de usi': 4,
                    'Consumul urban (l/100km)': 6.2,
                    'Consumul pe autostrada (l/100km)': 4.4,
                    'Consumul mixt (l/100km)': 5.1,
                    'Tipul Carburantului': "Diesel",
                    'Acceleratie (0-100km/h) (secunde)': 8.4,
                    'Viteza maxima (km/h)': 230,
                    'Standard ecologic': "Euro 5",
                    'Raport putere/greutate (CP/tona)': 116,
                    'Raport cuplu/greutate (Nm/tona)': 238.9,
                    'Capacitate cilindrica(cc)': 1968,
                    'Putere(hp)': 170,
                    'Cuplu(Nm)': 350,
                    'Codul Motor': "EA189 / CAHA",
                    'Configuratia Motorului': "4 cilindrii in linie, 4 valve per cilindru",
                    'Tipul de asiratie': "Turbosuflanta",
                    'Capacitate baie ulei(l)': 5,
                    'Masa maxima autorizata(kg)': 2015,
                    'Volumul minim al portbagajului(l)': 480,
                    'Volumul rezervorului(l)': 65,
                    'Lungime(mm)': 4703,
                    'Latime(mm)': 1826,
                    'Inaltime(mm)': 1427,
                    'Tractiune': "Fata",
                    'Tipul cutiei de viteze': "Cutie de viteze manuala - 6 trepte",
                    'Suspensie fata': "Suspensie multi-link independentă",
                    'Suspensie spate': "Suspensie independentă cu arc multi-legături cu stabilizator",
                    'Frane fata': "Discuri ventilate",
                    'Frane spate': "Disc",
                    'Emisii(g/km)':  134 ,
                },

                "2.0 TFSI 180hp": {
                    imagine: '/audia4b8sedan.jpg',
                    'Anii de fabricatie': "2007-2011",
                    'Numarul de scaune': 5,
                    'Numarul de usi': 4,
                    'Consumul urban (l/100km)': 9,
                    'Consumul pe autostrada (l/100km)': 5.2,
                    'Consumul mixt (l/100km)': 6.6,
                    'Tipul Carburantului': "Benzina",
                    'Acceleratie (0-100km/h) (secunde)': 7.9,
                    'Viteza maxima (km/h)': 236,
                    'Standard ecologic': "Euro 5",
                    'Raport putere/greutate (CP/tona)': 125.9,
                    'Raport cuplu/greutate (Nm/tona)': 223.8,
                    'Capacitate cilindrica(cc)': 1984,
                    'Putere(hp)': 180,
                    'Cuplu(Nm)': 320,
                    'Codul Motor': "EA888 / CDNB",
                    'Configuratia Motorului': "4 cilindrii in linie, 4 valve per cilindru",
                    'Tipul de asiratie': "Turbosuflanta",
                    'Capacitate baie ulei(l)': 4.6,
                    'Cantitatea lichidului de racire(l)': 7,
                    'Masa proprie(kg)': 1430,
                    'Masa maxima autorizata(kg)': 1980,
                    'Volumul minim al portbagajului(l)': 480,
                    'Volumul rezervorului(l)': 65,
                    'Lungime(mm)': 4703,
                    'Latime(mm)': 1826,
                    'Inaltime(mm)': 1427,
                    'Tractiune': "Fata",
                    'Tipul cutiei de viteze': "Cutie de viteze manuala - 6 trepte",
                    'Suspensie fata': "Suspensie multi-link independentă",
                    'Suspensie spate': "Suspensie independentă cu arc multi-legături cu stabilizator",
                    'Frane fata': "Discuri ventilate",
                    'Frane spate': "Disc",
                    'Emisii(g/km)': 154,
                },

                "2.0 TFSI 211hp": {
                    imagine: '/audia4b8sedan.jpg',
                    'Anii de fabricatie': "2007-2011",
                    'Numarul de scaune': 5,
                    'Numarul de usi': 4,
                    'Consumul urban (l/100km)': 9,
                    'Consumul pe autostrada (l/100km)': 5.2,
                    'Consumul mixt (l/100km)': 6.6,
                    'Tipul Carburantului': "Benzina",
                    'Acceleratie (0-100km/h) (secunde)': 6.9,
                    'Viteza maxima (km/h)': 250,
                    'Standard ecologic': "Euro 5",
                    'Raport putere/greutate (CP/tona)': 147,
                    'Raport cuplu/greutate (Nm/tona)': 243.9,
                    'Capacitate cilindrica(cc)': 1984,
                    'Putere(hp)': 211,
                    'Cuplu(Nm)': 350,
                    'Codul Motor': "EA888 / CAEB",
                    'Configuratia Motorului': "4 cilindrii in linie, 4 valve per cilindru",
                    'Tipul de asiratie': "Turbosuflanta",
                    'Capacitate baie ulei(l)': 4.6,
                    'Cantitatea lichidului de racire(l)': 7,
                    'Masa proprie(kg)': 1435,
                    'Masa maxima autorizata(kg)': 1985,
                    'Volumul minim al portbagajului(l)': 480,
                    'Volumul rezervorului(l)': 65,
                    'Lungime(mm)': 4703,
                    'Latime(mm)': 1826,
                    'Inaltime(mm)': 1427,
                    'Tractiune': "Fata",
                    'Tipul cutiei de viteze': "Cutie de viteze manuala - 6 trepte",
                    'Suspensie fata': "Suspensie multi-link independentă",
                    'Suspensie spate': "Suspensie independentă cu arc multi-legături cu stabilizator",
                    'Frane fata': "Discuri ventilate",
                    'Frane spate': "Disc",
                    'Emisii(g/km)': 154 ,
                },

                "2.7 TDI V6 190hp": {
                    imagine: '/audia4b8sedan.jpg',
                    'Anii de fabricatie': "2007-2011",
                    'Numarul de scaune': 5,
                    'Numarul de usi': 4,
                    'Consumul urban (l/100km)': 9,
                    'Consumul pe autostrada (l/100km)': 5.2,
                    'Consumul mixt (l/100km)': 6.6,
                    'Tipul Carburantului': "Diesel",
                    'Acceleratie (0-100km/h) (secunde)': 8.2,
                    'Viteza maxima (km/h)': 230,
                    'Standard ecologic': "Euro 5",
                    'Raport putere/greutate (CP/tona)': 121,
                    'Raport cuplu/greutate (Nm/tona)': 254.8,
                    'Capacitate cilindrica(cc)': 2697,
                    'Putere(hp)': 190,
                    'Cuplu(Nm)': 400,
                    'Codul Motor': "EA896 / CGKA",
                    'Configuratia Motorului': "6 cilindrii in V, 4 valve per cilindru",
                    'Tipul de asiratie': "Turbosuflanta",
                    'Capacitate baie ulei(l)': 6.9,
                    'Cantitatea lichidului de racire(l)': 12,
                    'Masa proprie(kg)': 1600,
                    'Masa maxima autorizata(kg)': 2120,
                    'Volumul minim al portbagajului(l)': 480,
                    'Volumul rezervorului(l)': 65,
                    'Lungime(mm)': 4703,
                    'Latime(mm)': 1826,
                    'Inaltime(mm)': 1427,
                    'Tractiune': "Fata",
                    'Tipul cutiei de viteze': "Cutie de viteze manuala - 6 trepte",
                    'Suspensie fata': "Suspensie multi-link independentă",
                    'Suspensie spate': "Suspensie independentă cu arc multi-legături cu stabilizator",
                    'Frane fata': "Discuri ventilate",
                    'Frane spate': "Disc",
                    'Emisii(g/km)': 159 ,
                },


                "3.0 TDI quattro 240hp": {
                    imagine: '/audia4b8sedan.jpg',
                    'Anii de fabricatie': "2007-2011",
                    'Numarul de scaune': 5,
                    'Numarul de usi': 4,
                    'Consumul urban (l/100km)': 9.6,
                    'Consumul pe autostrada (l/100km)': 5.4,
                    'Consumul mixt (l/100km)': 6.9,
                    'Tipul Carburantului': "Diesel",
                    'Acceleratie (0-100km/h) (secunde)': 6.1,
                    'Viteza maxima(km/h)': 250,
                    'Standard ecologic': "Euro 4",
                    'Raport putere/greutate (CP/tona)': 145,
                    'Raport cuplu/greutate (Nm/tona)': 302.1,
                    'Capacitate cilindrica(cc)': 2967,
                    'Putere(hp)': 240,
                    'Cuplu(Nm)': 500,
                    'Codul Motor': "EA896 / CCWA",
                    'Configuratia Motorului': "6 cilindrii in V, 4 valve per cilindru",
                    'Tipul de asiratie': "Turbosuflanta",
                    'Capacitate baie ulei(l)': 6.9,
                    'Cantitatea lichidului de racire(l)': 9,
                    'Masa proprie(kg)': 1655,
                    'Masa maxima autorizata(kg)': 2205,
                    'Volumul minim al portbagajului(l)': 480,
                    'Volumul rezervorului(l)': 65,
                    'Lungime(mm)': 4703,
                    'Latime(mm)': 1826,
                    'Inaltime(mm)': 1427,
                    'Tractiune': "Tractiune Integrala(4x4)",
                    'Tipul cutiei de viteze': "Cutie de viteze manuala - 6 trepte",
                    'Suspensie fata': "Suspensie multi-link independentă",
                    'Suspensie spate': "Suspensie independentă cu arc multi-legături cu stabilizator",
                    'Frane fata': "Discuri ventilate",
                    'Frane spate': "Disc",
                    'Emisii(g/km)': 183 ,
                },

                "3.2 FSI quattro 265hp": {
                    imagine: '/audia4b8sedan.jpg',
                    'Anii de fabricatie': "2007-2011",
                    'Numarul de scaune': 5,
                    'Numarul de usi': 4,
                    'Consumul urban (l/100km)': 13,
                    'Consumul pe autostrada (l/100km)': 6.6,
                    'Consumul mixt (l/100km)': 8.9,
                    'Tipul Carburantului': "Benzina",
                    'Acceleratie (0-100km/h) (secunde)': 6.2,
                    'Viteza maxima (km/h)': 250,
                    'Standard ecologic': "Euro 4",
                    'Raport putere/greutate (CP/tona)': 167.7,
                    'Raport cuplu/greutate (Nm/tona)': 208.9,
                    'Capacitate cilindrica(cc)': 3197,
                    'Putere(hp)': 265,
                    'Cuplu(Nm)': 330,
                    'Codul Motor': "EA390 / CALA",
                    'Configuratia Motorului': "6 cilindrii in V, 4 valve per cilindru",
                    'Tipul de asiratie': "Turbosuflanta",
                    'Capacitate baie ulei(l)': 6.2,
                    'Cantitatea lichidului de racire(l)': 9,
                    'Masa proprie(kg)': 1580,
                    'Masa maxima autorizata(kg)': 2130,
                    'Volumul minim al portbagajului(l)': 480,
                    'Volumul rezervorului(l)': 64,
                    'Lungime(mm)': 4703,
                    'Latime(mm)': 1826,
                    'Inaltime(mm)': 1427,
                    'Tractiune': "Tractiune Integrala(4x4)",
                    'Tipul cutiei de viteze': "Cutie de viteze manuala - 6 trepte",
                    'Suspensie fata': "Suspensie multi-link independentă",
                    'Suspensie spate': "Suspensie independentă cu arc multi-legături cu stabilizator",
                    'Frane fata': "Discuri ventilate",
                    'Frane spate': "Disc",
                    'Emisii(g/km)': 213 ,
                },
            },
        },
    },
    Mercedes: {
        "2007 Mercedes-Benz Clasa C (W204)": {
            "Sedan 4-door":{
                "C 180 Kompressor 1.8L 156hp":{
                    imagine:'/mbcclasssedan.jpg',
                    'Anii de fabricatie': "2007-2008",
                    'Numarul de scaune': 5,
                    'Numarul de usi': 4,
                    'Consumul urban (l/100km)': 10.5,
                    'Consumul pe autostrada (l/100km)': 5.6,
                    'Consumul mixt (l/100km)': 7.4,
                    'Tipul Carburantului': "Benzina",
                    'Acceleratie (0-100km/h) (secunde)': 9.5,
                    'Viteza maxima (km/h)': 223,
                    'Standard ecologic': "Euro 4",
                    'Raport putere/greutate (CP/tona)': 110.6,
                    'Raport cuplu/greutate (Nm/tona)': 163.1,
                    'Capacitate cilindrica(cc)': 1796,
                    'Putere(hp)': 156,
                    'Cuplu(Nm)': 230,
                    'Codul Motor': "M 271.952",
                    'Configuratia Motorului': "4 cilindrii in linie, 4 valve per cilindru",
                    'Tipul de asiratie': "Turbosuflanta mecanica",
                    'Capacitate baie ulei(l)': 5.5,
                    'Cantitatea lichidului de racire(l)': 3.8,
                    'Masa proprie(kg)': 1410,
                    'Masa maxima autorizata(kg)': 1970,
                    'Volumul minim al portbagajului(l)': 475,
                    'Volumul rezervorului(l)': 66,
                    'Lungime(mm)': 4581,
                    'Latime(mm)': 1770,
                    'Inaltime(mm)': 1447,
                    'Tractiune': "Tractiune Spate",
                    'Tipul cutiei de viteze': "Cutie de viteze manuala - 6 trepte",
                    'Suspensie fata': "independent de tip McPherson, stabilizator transversal",
                    'Suspensie spate': "Suspensie multi-link independentă, stabilizator transversal",
                    'Frane fata': "Discuri ventilate",
                    'Frane spate': "Disc",
                    'Emisii(g/km)': 177 ,
                },
                "C 200 CDI 2.2L 136hp":{
                    imagine:'/mbcclasssedan.jpg',
                    'Anii de fabricatie': "2007-2009",
                    'Numarul de scaune': 5,
                    'Numarul de usi': 4,
                    'Consumul urban (l/100km)': 7.7,
                    'Consumul pe autostrada (l/100km)': 4.5,
                    'Consumul mixt (l/100km)': 5.7,
                    'Tipul Carburantului': "Diesel",
                    'Acceleratie (0-100km/h) (secunde)': 10.4,
                    'Viteza maxima (km/h)': 215,
                    'Standard ecologic': "Euro 4",
                    'Raport putere/greutate (CP/tona)': 91.6,
                    'Raport cuplu/greutate (Nm/tona)': 181.8,
                    'Capacitate cilindrica(cc)': 2148,
                    'Putere(hp)': 136,
                    'Cuplu(Nm)': 270,
                    'Codul Motor': "OM 646.811",
                    'Configuratia Motorului': "4 cilindrii in linie, 4 valve per cilindru",
                    'Tipul de asiratie': "Turbosuflanta",
                    'Capacitate baie ulei(l)': 6.5,
                    'Cantitatea lichidului de racire(l)': 6,
                    'Masa proprie(kg)': 1485,
                    'Masa maxima autorizata(kg)': 2045,
                    'Volumul minim al portbagajului(l)': 475,
                    'Volumul rezervorului(l)': 66,
                    'Lungime(mm)': 4581,
                    'Latime(mm)': 1770,
                    'Inaltime(mm)': 1447,
                    'Tractiune': "Tractiune Spate",
                    'Tipul cutiei de viteze': "Cutie de viteze manuala - 6 trepte",
                    'Suspensie fata': "independent de tip McPherson, stabilizator transversal",
                    'Suspensie spate': "Suspensie multi-link independentă, stabilizator transversal",
                    'Frane fata': "Discuri ventilate",
                    'Frane spate': "Disc",
                    'Emisii(g/km)': 150 ,
                },
                "C 200 CGI 1.8L BlueEFFICIENCY 184hp":{
                    imagine:'/mbcclasssedan.jpg',
                    'Anii de fabricatie': "2010-2011",
                    'Numarul de scaune': 5,
                    'Numarul de usi': 4,
                    'Consumul urban (l/100km)': 10,
                    'Consumul pe autostrada (l/100km)': 5.5,
                    'Consumul mixt (l/100km)': 6.8,
                    'Tipul Carburantului': "Benzina",
                    'Acceleratie (0-100km/h) (secunde)': 8.2,
                    'Viteza maxima (km/h)': 237,
                    'Standard ecologic': "Euro 5",
                    'Raport putere/greutate (CP/tona)': 129.1,
                    'Raport cuplu/greutate (Nm/tona)': 189.5,
                    'Capacitate cilindrica(cc)': 1796,
                    'Putere(hp)': 184,
                    'Cuplu(Nm)': 270,
                    'Codul Motor': "M 271.820",
                    'Configuratia Motorului': "4 cilindrii in linie, 4 valve per cilindru",
                    'Tipul de asiratie': "Turbosuflanta",
                    'Capacitate baie ulei(l)': 5.5,
                    'Cantitatea lichidului de racire(l)': 8,
                    'Masa proprie(kg)': 1425,
                    'Masa maxima autorizata(kg)': 2005,
                    'Volumul minim al portbagajului(l)': 475,
                    'Volumul rezervorului(l)': 59,
                    'Lungime(mm)': 4581,
                    'Latime(mm)': 1770,
                    'Inaltime(mm)': 1447,
                    'Tractiune': "Tractiune Spate",
                    'Tipul cutiei de viteze': "Cutie de viteze manuala - 6 trepte",
                    'Suspensie fata': "independent de tip McPherson, stabilizator transversal",
                    'Suspensie spate': "Suspensie multi-link independentă, stabilizator transversal",
                    'Frane fata': "Discuri ventilate",
                    'Frane spate': "Disc",
                    'Emisii(g/km)': 160 ,
                },
                "C 200 Kompressor 1.8L 184hp":{
                    imagine:'/mbcclasssedan.jpg',
                    'Anii de fabricatie': "2007-2010",
                    'Numarul de scaune': 5,
                    'Numarul de usi': 4,
                    'Consumul urban (l/100km)': 10.5,
                    'Consumul pe autostrada (l/100km)': 5.8,
                    'Consumul mixt (l/100km)': 7.6,
                    'Tipul Carburantului': "Benzina",
                    'Acceleratie (0-100km/h) (secunde)': 8.6,
                    'Viteza maxima (km/h)': 235,
                    'Standard ecologic': "Euro 4",
                    'Raport putere/greutate (CP/tona)': 130,
                    'Raport cuplu/greutate (Nm/tona)': 176.7,
                    'Capacitate cilindrica(cc)': 1796,
                    'Putere(hp)': 184,
                    'Cuplu(Nm)': 250,
                    'Codul Motor': "M 271.950",
                    'Configuratia Motorului': "4 cilindrii in linie, 4 valve per cilindru",
                    'Tipul de asiratie': "Turbosuflanta mecanica",
                    'Capacitate baie ulei(l)': 5.5,
                    'Cantitatea lichidului de racire(l)': 3.8,
                    'Masa proprie(kg)': 1415,
                    'Masa maxima autorizata(kg)': 1975,
                    'Volumul minim al portbagajului(l)': 475,
                    'Volumul rezervorului(l)': 66,
                    'Lungime(mm)': 4581,
                    'Latime(mm)': 1770,
                    'Inaltime(mm)': 1447,
                    'Tractiune': "Tractiune Spate",
                    'Tipul cutiei de viteze': "Cutie de viteze manuala - 6 trepte",
                    'Suspensie fata': "independent de tip McPherson, stabilizator transversal",
                    'Suspensie spate': "Suspensie multi-link independentă, stabilizator transversal",
                    'Frane fata': "Discuri ventilate",
                    'Frane spate': "Disc",
                    'Emisii(g/km)': 180 ,
                },
                "C 220 CDI 2.2L 170hp":{
                    imagine:'/mbcclasssedan.jpg',
                    'Anii de fabricatie': "2007-2009",
                    'Numarul de scaune': 5,
                    'Numarul de usi': 4,
                    'Consumul urban (l/100km)': 8,
                    'Consumul pe autostrada (l/100km)': 4.7,
                    'Consumul mixt (l/100km)': 6,
                    'Tipul Carburantului': "Diesel",
                    'Acceleratie (0-100km/h) (secunde)': 8.5,
                    'Viteza maxima (km/h)': 229,
                    'Standard ecologic': "Euro 4",
                    'Raport putere/greutate (CP/tona)': 112.6,
                    'Raport cuplu/greutate (Nm/tona)': 264.9,
                    'Capacitate cilindrica(cc)': 2148,
                    'Putere(hp)': 170,
                    'Cuplu(Nm)': 400,
                    'Codul Motor': "OM 646.811",
                    'Configuratia Motorului': "4 cilindrii in linie, 4 valve per cilindru",
                    'Tipul de asiratie': "Turbosuflanta",
                    'Capacitate baie ulei(l)': 6.5,
                    'Cantitatea lichidului de racire(l)': 6,
                    'Masa proprie(kg)': 1510,
                    'Masa maxima autorizata(kg)': 2070,
                    'Volumul minim al portbagajului(l)': 475,
                    'Volumul rezervorului(l)': 66,
                    'Lungime(mm)': 4581,
                    'Latime(mm)': 1770,
                    'Inaltime(mm)': 1447,
                    'Tractiune': "Tractiune Spate",
                    'Tipul cutiei de viteze': "Cutie de viteze manuala - 6 trepte",
                    'Suspensie fata': "independent de tip McPherson, stabilizator transversal",
                    'Suspensie spate': "Suspensie multi-link independentă, stabilizator transversal",
                    'Frane fata': "Discuri ventilate",
                    'Frane spate': "Disc",
                    'Emisii(g/km)': 156 ,
                },
                "C 230 V6 2.5L 204hp":{
                    imagine:'/mbcclasssedan.jpg',
                    'Anii de fabricatie': "2007-2009",
                    'Numarul de scaune': 5,
                    'Numarul de usi': 4,
                    'Consumul urban (l/100km)': 13.3,
                    'Consumul pe autostrada (l/100km)': 6.7,
                    'Consumul mixt (l/100km)': 9.1,
                    'Tipul Carburantului': "Benzina",
                    'Acceleratie (0-100km/h) (secunde)': 8.4,
                    'Viteza maxima (km/h)': 240,
                    'Standard ecologic': "Euro 4",
                    'Raport putere/greutate (CP/tona)': 139.2,
                    'Raport cuplu/greutate (Nm/tona)': 167.2,
                    'Capacitate cilindrica(cc)': 2496,
                    'Putere(hp)': 204,
                    'Cuplu(Nm)': 245,
                    'Codul Motor': "M 272.921",
                    'Configuratia Motorului': "6 cilindrii in V, 4 valve per cilindru",
                    'Tipul de asiratie': "Aspirat natural",
                    'Capacitate baie ulei(l)': 8,
                    'Cantitatea lichidului de racire(l)': 4.8,
                    'Masa proprie(kg)': 1465,
                    'Masa maxima autorizata(kg)': 2025,
                    'Volumul minim al portbagajului(l)': 475,
                    'Volumul rezervorului(l)': 66,
                    'Lungime(mm)': 4581,
                    'Latime(mm)': 1770,
                    'Inaltime(mm)': 1447,
                    'Tractiune': "Tractiune Spate",
                    'Tipul cutiei de viteze': "Cutie de viteze manuala - 6 trepte",
                    'Suspensie fata': "independent de tip McPherson, stabilizator transversal",
                    'Suspensie spate': "Suspensie multi-link independentă, stabilizator transversal",
                    'Frane fata': "Discuri ventilate",
                    'Frane spate': "Disc",
                    'Emisii(g/km)': 216 ,
                },
                "C 280 V6 3.0L 231hp":{
                    imagine:'/mbcclasssedan.jpg',
                    'Anii de fabricatie': "2007-2009",
                    'Numarul de scaune': 5,
                    'Numarul de usi': 4,
                    'Consumul urban (l/100km)': 13.4,
                    'Consumul pe autostrada (l/100km)': 6.8,
                    'Consumul mixt (l/100km)': 9.2,
                    'Tipul Carburantului': "Benzina",
                    'Acceleratie (0-100km/h) (secunde)': 7.3,
                    'Viteza maxima (km/h)': 250,
                    'Standard ecologic': "Euro 4",
                    'Raport putere/greutate (CP/tona)': 156.1,
                    'Raport cuplu/greutate (Nm/tona)': 202.7,
                    'Capacitate cilindrica(cc)': 2996,
                    'Putere(hp)': 231,
                    'Cuplu(Nm)': 300,
                    'Codul Motor': "M 272.947",
                    'Configuratia Motorului': "6 cilindrii in V, 4 valve per cilindru",
                    'Tipul de asiratie': "Aspirat natural",
                    'Capacitate baie ulei(l)': 8,
                    'Cantitatea lichidului de racire(l)': 4.8,
                    'Masa proprie(kg)': 1480,
                    'Masa maxima autorizata(kg)': 2040,
                    'Volumul minim al portbagajului(l)': 475,
                    'Volumul rezervorului(l)': 66,
                    'Lungime(mm)': 4581,
                    'Latime(mm)': 1770,
                    'Inaltime(mm)': 1447,
                    'Tractiune': "Tractiune Spate",
                    'Tipul cutiei de viteze': "Cutie de viteze manuala - 6 trepte",
                    'Suspensie fata': "independent de tip McPherson, stabilizator transversal",
                    'Suspensie spate': "Suspensie multi-link independentă, stabilizator transversal",
                    'Frane fata': "Discuri ventilate",
                    'Frane spate': "Disc",
                    'Emisii(g/km)': 220 ,
                },
                "C 300 V6 3.0L 231hp":{
                    imagine:'/mbcclasssedan.jpg',
                    'Anii de fabricatie': "2009-2011",
                    'Numarul de scaune': 5,
                    'Numarul de usi': 4,
                    'Consumul urban (l/100km)': 13.7,
                    'Consumul pe autostrada (l/100km)': 6.9,
                    'Consumul mixt (l/100km)': 9.4,
                    'Tipul Carburantului': "Benzina",
                    'Acceleratie (0-100km/h) (secunde)': 7.3,
                    'Viteza maxima (km/h)': 250,
                    'Standard ecologic': "Euro 5",
                    'Raport putere/greutate (CP/tona)': 156.1,
                    'Raport cuplu/greutate (Nm/tona)': 202.7,
                    'Capacitate cilindrica(cc)': 2996,
                    'Putere(hp)': 231,
                    'Cuplu(Nm)': 300,
                    'Codul Motor': "M 272.947",
                    'Configuratia Motorului': "6 cilindrii in V, 4 valve per cilindru",
                    'Tipul de asiratie': "Aspirat natural",
                    'Capacitate baie ulei(l)': 8,
                    'Cantitatea lichidului de racire(l)': 4.8,
                    'Masa proprie(kg)': 1480,
                    'Masa maxima autorizata(kg)': 2040,
                    'Volumul minim al portbagajului(l)': 475,
                    'Volumul rezervorului(l)': 66,
                    'Lungime(mm)': 4581,
                    'Latime(mm)': 1770,
                    'Inaltime(mm)': 1447,
                    'Tractiune': "Tractiune Spate",
                    'Tipul cutiei de viteze': "Cutie de viteze manuala - 6 trepte",
                    'Suspensie fata': "independent de tip McPherson, stabilizator transversal",
                    'Suspensie spate': "Suspensie multi-link independentă, stabilizator transversal",
                    'Frane fata': "Discuri ventilate",
                    'Frane spate': "Disc",
                    'Emisii(g/km)': 220 ,
                },
                "C 320 CDI V6 3.0L 224hp":{
                    imagine:'/mbcclasssedan.jpg',
                    'Anii de fabricatie': "2007-2009",
                    'Numarul de scaune': 5,
                    'Numarul de usi': 4,
                    'Consumul urban (l/100km)': 9.2,
                    'Consumul pe autostrada (l/100km)': 5.5,
                    'Consumul mixt (l/100km)': 6.9,
                    'Tipul Carburantului': "Diesel",
                    'Acceleratie (0-100km/h) (secunde)': 7.7,
                    'Viteza maxima (km/h)': 250,
                    'Standard ecologic': "Euro 4",
                    'Raport putere/greutate (CP/tona)': 137.8,
                    'Raport cuplu/greutate (Nm/tona)': 313.8,
                    'Capacitate cilindrica(cc)': 2987,
                    'Putere(hp)': 224,
                    'Cuplu(Nm)': 510,
                    'Codul Motor': "OM 642.960",
                    'Configuratia Motorului': "6 cilindrii in V, 4 valve per cilindru",
                    'Tipul de asiratie': "Turbosuflanta",
                    'Capacitate baie ulei(l)': 8,
                    'Cantitatea lichidului de racire(l)': 5.7,
                    'Masa proprie(kg)': 1625,
                    'Masa maxima autorizata(kg)': 2185,
                    'Volumul minim al portbagajului(l)': 475,
                    'Volumul rezervorului(l)': 66,
                    'Lungime(mm)': 4581,
                    'Latime(mm)': 1770,
                    'Inaltime(mm)': 1447,
                    'Tractiune': "Tractiune Spate",
                    'Tipul cutiei de viteze': "Cutie de viteze manuala - 6 trepte",
                    'Suspensie fata': "independent de tip McPherson, stabilizator transversal",
                    'Suspensie spate': "Suspensie multi-link independentă, stabilizator transversal",
                    'Frane fata': "Discuri ventilate",
                    'Frane spate': "Disc",
                    'Emisii(g/km)': 185 ,
                },
                "C 350 CDI 3.0L BlueEFFICIENCY 4MATIC 7G-TRONIC 231hp":{
                    imagine:'/mbcclasssedan.jpg',
                    'Anii de fabricatie': "2009-2011",
                    'Numarul de scaune': 5,
                    'Numarul de usi': 4,
                    'Consumul urban (l/100km)': 9.2,
                    'Consumul pe autostrada (l/100km)': 6,
                    'Consumul mixt (l/100km)': 7,
                    'Tipul Carburantului': "Diesel",
                    'Acceleratie (0-100km/h) (secunde)': 6.4,
                    'Viteza maxima (km/h)': 250,
                    'Standard ecologic': "Euro 5",
                    'Raport putere/greutate (CP/tona)': 137.1,
                    'Raport cuplu/greutate (Nm/tona)': 320.5,
                    'Capacitate cilindrica(cc)': 2987,
                    'Putere(hp)': 231,
                    'Cuplu(Nm)': 540,
                    'Codul Motor': "OM 642.830",
                    'Configuratia Motorului': "6 cilindrii in V, 4 valve per cilindru",
                    'Tipul de asiratie': "Turbosuflanta",
                    'Capacitate baie ulei(l)': 8,
                    'Cantitatea lichidului de racire(l)': 5.7,
                    'Masa proprie(kg)': 1685,
                    'Masa maxima autorizata(kg)': 2265,
                    'Volumul minim al portbagajului(l)': 475,
                    'Volumul rezervorului(l)': 66,
                    'Lungime(mm)': 4581,
                    'Latime(mm)': 1770,
                    'Inaltime(mm)': 1447,
                    'Tractiune': "Tracţiune integrală (4x4)",
                    'Tipul cutiei de viteze': "7 trepte, cutie automată G-TRONIC",
                    'Suspensie fata': "independent de tip McPherson, stabilizator transversal",
                    'Suspensie spate': "Suspensie multi-link independentă, stabilizator transversal",
                    'Frane fata': "Discuri ventilate",
                    'Frane spate': "Disc",
                    'Emisii(g/km)': 185 ,
                },
                "C 350 V6 3.5L 7G-TRONIC 272hp":{
                    imagine:'/mbcclasssedan.jpg',
                    'Anii de fabricatie': "2009-2011",
                    'Numarul de scaune': 5,
                    'Numarul de usi': 4,
                    'Consumul urban (l/100km)': 14.2,
                    'Consumul pe autostrada (l/100km)': 7.4,
                    'Consumul mixt (l/100km)': 10,
                    'Tipul Carburantului': "Benzina",
                    'Acceleratie (0-100km/h) (secunde)': 6.4,
                    'Viteza maxima (km/h)': 250,
                    'Standard ecologic': "Euro 5",
                    'Raport putere/greutate (CP/tona)': 177.2,
                    'Raport cuplu/greutate (Nm/tona)': 228,
                    'Capacitate cilindrica(cc)': 3498,
                    'Putere(hp)': 272,
                    'Cuplu(Nm)': 350,
                    'Codul Motor': "M 272.961",
                    'Configuratia Motorului': "6 cilindrii in V, 4 valve per cilindru",
                    'Tipul de asiratie': "Aspirat natural",
                    'Capacitate baie ulei(l)': 8,
                    'Cantitatea lichidului de racire(l)': 4.8,
                    'Masa proprie(kg)': 1535,
                    'Masa maxima autorizata(kg)': 2095,
                    'Volumul minim al portbagajului(l)': 475,
                    'Volumul rezervorului(l)': 66,
                    'Lungime(mm)': 4581,
                    'Latime(mm)': 1770,
                    'Inaltime(mm)': 1447,
                    'Tractiune': "Tracţiune spate",
                    'Tipul cutiei de viteze': "7 trepte, cutie automată G-TRONIC",
                    'Suspensie fata': "independent de tip McPherson, stabilizator transversal",
                    'Suspensie spate': "Suspensie multi-link independentă, stabilizator transversal",
                    'Frane fata': "Discuri ventilate",
                    'Frane spate': "Discuri ventilate",
                    'Emisii(g/km)': 232 ,
                }
            }
        }
    },
    "Alfa Romeo":{
        "2005 Alfa Romeo 159":{
            "Sedan 4-door":{
                "1.75 TBi 200hp":{
                    imagine:'/alfa159sedan.jpg',
                    'Anii de fabricatie': "2009-2011",
                    'Numarul de scaune': 5,
                    'Numarul de usi': 4,
                    'Consumul urban (l/100km)': 11.8,
                    'Consumul pe autostrada (l/100km)': 6,
                    'Consumul mixt (l/100km)': 8.1,
                    'Tipul Carburantului': "Benzina",
                    'Acceleratie (0-100km/h) (secunde)': 7.7,
                    'Viteza maxima (km/h)': 235,
                    'Standard ecologic': "Euro 5",
                    'Raport putere/greutate (CP/tona)': 139.9,
                    'Raport cuplu/greutate (Nm/tona)': 223.8,
                    'Capacitate cilindrica(cc)': 1742,
                    'Putere(hp)': 200,
                    'Cuplu(Nm)': 320,
                    'Codul Motor': "939B1000",
                    'Configuratia Motorului': "4 cilindrii in linie, 4 valve per cilindru",
                    'Tipul de asiratie': "Turbosuflanta",
                    'Capacitate baie ulei(l)': 4.25,
                    'Cantitatea lichidului de racire(l)': 6.6,
                    'Masa proprie(kg)': 1430,
                    'Masa maxima autorizata(kg)': 1930,
                    'Volumul minim al portbagajului(l)': 405,
                    'Volumul rezervorului(l)': 70,
                    'Lungime(mm)': 4660,
                    'Latime(mm)': 1828,
                    'Inaltime(mm)': 1417,
                    'Tractiune': "Tracţiune fata",
                    'Tipul cutiei de viteze': "6 trepte, cutie manuală",
                    'Suspensie fata': "iades dublu",
                    'Suspensie spate': "Suspensie multi-link independentă",
                    'Frane fata': "Discuri ventilate",
                    'Frane spate': "Discuri ventilate",
                    'Emisii(g/km)': 189,
                },
                "1.8 MPI 140hp":{
                    imagine:'/alfa159sedan.jpg',
                    'Anii de fabricatie': "2005-2010",
                    'Numarul de scaune': 5,
                    'Numarul de usi': 4,
                    'Consumul urban (l/100km)': 10.3,
                    'Consumul pe autostrada (l/100km)': 6,
                    'Consumul mixt (l/100km)': 7.6,
                    'Tipul Carburantului': "Benzina",
                    'Acceleratie (0-100km/h) (secunde)': 10.2,
                    'Viteza maxima (km/h)': 208,
                    'Standard ecologic': "Euro 4",
                    'Raport putere/greutate (CP/tona)': 101.1,
                    'Raport cuplu/greutate (Nm/tona)': 126.4,
                    'Capacitate cilindrica(cc)': 1796,
                    'Putere(hp)': 140,
                    'Cuplu(Nm)': 175,
                    'Codul Motor': "939 A4.000",
                    'Configuratia Motorului': "4 cilindrii in linie, 4 valve per cilindru",
                    'Tipul de asiratie': "Aspirat natural",
                    'Capacitate baie ulei(l)': 4.5,
                    'Cantitatea lichidului de racire(l)': 8,
                    'Masa proprie(kg)': 1385,
                    'Masa maxima autorizata(kg)': 1935,
                    'Volumul minim al portbagajului(l)': 405,
                    'Volumul rezervorului(l)': 70,
                    'Lungime(mm)': 4660,
                    'Latime(mm)': 1828,
                    'Inaltime(mm)': 1417,
                    'Tractiune': "Tracţiune fata",
                    'Tipul cutiei de viteze': "5 trepte, cutie manuală",
                    'Suspensie fata': "Suspensie multi-link independentă",
                    'Suspensie spate': "Suspensie multi-link independentă",
                    'Frane fata': "Discuri ventilate",
                    'Frane spate': "Disc",
                    'Emisii(g/km)': 179,
                },
                "1.9 JTDM 8V 120hp":{
                    imagine:'/alfa159sedan.jpg',
                    'Anii de fabricatie': "2005-2009",
                    'Numarul de scaune': 5,
                    'Numarul de usi': 4,
                    'Consumul urban (l/100km)': 7.8,
                    'Consumul pe autostrada (l/100km)': 4.8,
                    'Consumul mixt (l/100km)': 5.9,
                    'Tipul Carburantului': "Diesel",
                    'Acceleratie (0-100km/h) (secunde)': 10.7,
                    'Viteza maxima (km/h)': 193,
                    'Standard ecologic': "Euro 4",
                    'Raport putere/greutate (CP/tona)': 81.1,
                    'Raport cuplu/greutate (Nm/tona)': 189.2,
                    'Capacitate cilindrica(cc)': 1910,
                    'Putere(hp)': 120,
                    'Cuplu(Nm)': 280,
                    'Codul Motor': "939 A1.000",
                    'Configuratia Motorului': "4 cilindrii in linie, 4 valve per cilindru",
                    'Tipul de asiratie': "Turbosuflanta",
                    'Capacitate baie ulei(l)': 4.6,
                    'Cantitatea lichidului de racire(l)': 7.5,
                    'Masa proprie(kg)': 1480,
                    'Masa maxima autorizata(kg)': 2030,
                    'Volumul minim al portbagajului(l)': 405,
                    'Volumul rezervorului(l)': 70,
                    'Lungime(mm)': 4660,
                    'Latime(mm)': 1828,
                    'Inaltime(mm)': 1417,
                    'Tractiune': "Tracţiune fata",
                    'Tipul cutiei de viteze': "6 trepte, cutie manuală",
                    'Suspensie fata': "Suspensie multi-link independentă",
                    'Suspensie spate': "Suspensie multi-link independentă",
                    'Frane fata': "Discuri ventilate",
                    'Frane spate': "Disc",
                    'Emisii(g/km)': 157,
                },
                "1.9 JTDM 16V 150hp":{
                    imagine:'/alfa159sedan.jpg',
                    'Anii de fabricatie': "2005-2010",
                    'Numarul de scaune': 5,
                    'Numarul de usi': 4,
                    'Consumul urban (l/100km)': 8.1,
                    'Consumul pe autostrada (l/100km)': 4.8,
                    'Consumul mixt (l/100km)': 6,
                    'Tipul Carburantului': "Diesel",
                    'Acceleratie (0-100km/h) (secunde)': 9.4,
                    'Viteza maxima (km/h)': 210,
                    'Standard ecologic': "Euro 4",
                    'Raport putere/greutate (CP/tona)': 97.7,
                    'Raport cuplu/greutate (Nm/tona)': 208.5,
                    'Capacitate cilindrica(cc)': 1910,
                    'Putere(hp)': 150,
                    'Cuplu(Nm)': 320,
                    'Codul Motor': "939 A2.000",
                    'Configuratia Motorului': "4 cilindrii in linie, 4 valve per cilindru",
                    'Tipul de asiratie': "Turbosuflanta",
                    'Capacitate baie ulei(l)': 4.6,
                    'Cantitatea lichidului de racire(l)': 7.5,
                    'Masa proprie(kg)': 1535,
                    'Masa maxima autorizata(kg)': 2055,
                    'Volumul minim al portbagajului(l)': 405,
                    'Volumul rezervorului(l)': 70,
                    'Lungime(mm)': 4660,
                    'Latime(mm)': 1828,
                    'Inaltime(mm)': 1417,
                    'Tractiune': "Tracţiune fata",
                    'Tipul cutiei de viteze': "6 trepte, cutie manuală",
                    'Suspensie fata': "Suspensie multi-link independentă",
                    'Suspensie spate': "Suspensie multi-link independentă",
                    'Frane fata': "Discuri ventilate",
                    'Frane spate': "Disc",
                    'Emisii(g/km)': 159,
                },
                "1.9 JTS 160hp":{
                    imagine:'/alfa159sedan.jpg',
                    'Anii de fabricatie': "2005-2009",
                    'Numarul de scaune': 5,
                    'Numarul de usi': 4,
                    'Consumul urban (l/100km)': 12.2,
                    'Consumul pe autostrada (l/100km)': 6.6,
                    'Consumul mixt (l/100km)': 8.7,
                    'Tipul Carburantului': "Benzina",
                    'Acceleratie (0-100km/h) (secunde)': 9.7,
                    'Viteza maxima (km/h)': 212,
                    'Standard ecologic': "Euro 4",
                    'Raport putere/greutate (CP/tona)': 108.1,
                    'Raport cuplu/greutate (Nm/tona)': 128.4,
                    'Capacitate cilindrica(cc)': 1859,
                    'Putere(hp)': 160,
                    'Cuplu(Nm)': 190,
                    'Codul Motor': "939 A6.000",
                    'Configuratia Motorului': "4 cilindrii in linie, 4 valve per cilindru",
                    'Tipul de asiratie': "Aspirat natural",
                    'Capacitate baie ulei(l)': 5.4,
                    'Cantitatea lichidului de racire(l)': 8.15,
                    'Masa proprie(kg)': 1480,
                    'Masa maxima autorizata(kg)': 2000,
                    'Volumul minim al portbagajului(l)': 405,
                    'Volumul rezervorului(l)': 70,
                    'Lungime(mm)': 4660,
                    'Latime(mm)': 1828,
                    'Inaltime(mm)': 1417,
                    'Tractiune': "Tracţiune fata",
                    'Tipul cutiei de viteze': "6 trepte, cutie manuală",
                    'Suspensie fata': "Suspensie multi-link independentă",
                    'Suspensie spate': "Suspensie multi-link independentă",
                    'Frane fata': "Discuri ventilate",
                    'Frane spate': "Disc",
                    'Emisii(g/km)': 205,
                },
                "2.0 JTDM 16V 170hp":{
                    imagine:'/alfa159sedan.jpg',
                    'Anii de fabricatie': "2009-2011",
                    'Numarul de scaune': 5,
                    'Numarul de usi': 4,
                    'Consumul urban (l/100km)': 6.9,
                    'Consumul pe autostrada (l/100km)': 4.3,
                    'Consumul mixt (l/100km)': 5.3,
                    'Tipul Carburantului': "Diesel",
                    'Acceleratie (0-100km/h) (secunde)': 8.8,
                    'Viteza maxima (km/h)': 218,
                    'Standard ecologic': "Euro 5",
                    'Raport putere/greutate (CP/tona)': 114.1,
                    'Raport cuplu/greutate (Nm/tona)': 241.6,
                    'Capacitate cilindrica(cc)': 1956,
                    'Putere(hp)': 170,
                    'Cuplu(Nm)': 360,
                    'Codul Motor': "939 B3.000",
                    'Configuratia Motorului': "4 cilindrii in linie, 4 valve per cilindru",
                    'Tipul de asiratie': "Turbosuflanta",
                    'Capacitate baie ulei(l)': 4.9,
                    'Cantitatea lichidului de racire(l)': 6.1,
                    'Masa proprie(kg)': 1490,
                    'Masa maxima autorizata(kg)': 2040,
                    'Volumul minim al portbagajului(l)': 405,
                    'Volumul rezervorului(l)': 70,
                    'Lungime(mm)': 4660,
                    'Latime(mm)': 1828,
                    'Inaltime(mm)': 1417,
                    'Tractiune': "Tracţiune fata",
                    'Tipul cutiei de viteze': "6 trepte, cutie manuală",
                    'Suspensie fata': "Suspensie multi-link independentă",
                    'Suspensie spate': "Suspensie multi-link independentă",
                    'Frane fata': "Discuri ventilate",
                    'Frane spate': "Disc",
                    'Emisii(g/km)': 139,
                },
                "2.2 JTS 185hp":{
                    imagine:'/alfa159sedan.jpg',
                    'Anii de fabricatie': "2005-2009",
                    'Numarul de scaune': 5,
                    'Numarul de usi': 4,
                    'Consumul urban (l/100km)': 12.8,
                    'Consumul pe autostrada (l/100km)': 7.1,
                    'Consumul mixt (l/100km)': 9.2,
                    'Tipul Carburantului': "Benzina",
                    'Acceleratie (0-100km/h) (secunde)': 8.7,
                    'Viteza maxima (km/h)': 224,
                    'Standard ecologic': "Euro 4",
                    'Raport putere/greutate (CP/tona)': 128,
                    'Raport cuplu/greutate (Nm/tona)': 159.2,
                    'Capacitate cilindrica(cc)': 2198,
                    'Putere(hp)': 185,
                    'Cuplu(Nm)': 230,
                    'Codul Motor': "939 A5.000",
                    'Configuratia Motorului': "4 cilindrii in linie, 4 valve per cilindru",
                    'Tipul de asiratie': "Aspirat natural",
                    'Capacitate baie ulei(l)': 5.4,
                    'Cantitatea lichidului de racire(l)': 8.15,
                    'Masa proprie(kg)': 1445,
                    'Masa maxima autorizata(kg)': 1995,
                    'Volumul minim al portbagajului(l)': 405,
                    'Volumul rezervorului(l)': 70,
                    'Lungime(mm)': 4660,
                    'Latime(mm)': 1828,
                    'Inaltime(mm)': 1417,
                    'Tractiune': "Tracţiune fata",
                    'Tipul cutiei de viteze': "6 trepte, cutie manuală",
                    'Suspensie fata': "Suspensie multi-link independentă",
                    'Suspensie spate': "Suspensie multi-link independentă",
                    'Frane fata': "Discuri ventilate",
                    'Frane spate': "Disc",
                    'Emisii(g/km)': 218,
                },
                "2.4 JTDM Q-Tronic 200hp":{
                    imagine:'/alfa159sedan.jpg',
                    'Anii de fabricatie': "2006-2010",
                    'Numarul de scaune': 5,
                    'Numarul de usi': 4,
                    'Consumul urban (l/100km)': 11.4,
                    'Consumul pe autostrada (l/100km)': 5.8,
                    'Consumul mixt (l/100km)': 7.9,
                    'Tipul Carburantului': "Motorina",
                    'Acceleratie (0-100km/h) (secunde)': 8.3,
                    'Viteza maxima (km/h)': 225,
                    'Standard ecologic': "Euro 4",
                    'Raport putere/greutate (CP/tona)': 124.6,
                    'Raport cuplu/greutate (Nm/tona)': 249.2,
                    'Capacitate cilindrica(cc)': 2387,
                    'Putere(hp)': 200,
                    'Cuplu(Nm)': 400,
                    'Codul Motor': "939 A3.000",
                    'Configuratia Motorului': "5 cilindrii in linie, 4 valve per cilindru",
                    'Tipul de asiratie': "Turbosuflanta",
                    'Capacitate baie ulei(l)': 6.4,
                    'Cantitatea lichidului de racire(l)': 7.35,
                    'Masa proprie(kg)': 1605,
                    'Masa maxima autorizata(kg)': 2155,
                    'Volumul minim al portbagajului(l)': 405,
                    'Volumul rezervorului(l)': 70,
                    'Lungime(mm)': 4660,
                    'Latime(mm)': 1828,
                    'Inaltime(mm)': 1417,
                    'Tractiune': "Tracţiune fata",
                    'Tipul cutiei de viteze': "6 trepte, cutie automată",
                    'Suspensie fata': "Suspensie multi-link independentă",
                    'Suspensie spate': "Suspensie multi-link independentă",
                    'Frane fata': "Discuri ventilate",
                    'Frane spate': "Discuri ventilate",
                    'Emisii(g/km)': 208,
                },
                "2.4 JTDM 20V 210hp":{
                    imagine:'/alfa159sedan.jpg',
                    'Anii de fabricatie': "2007-2009",
                    'Numarul de scaune': 5,
                    'Numarul de usi': 4,
                    'Consumul urban (l/100km)': 9.2,
                    'Consumul pe autostrada (l/100km)': 5.4,
                    'Consumul mixt (l/100km)': 6.8,
                    'Tipul Carburantului': "Motorina",
                    'Acceleratie (0-100km/h) (secunde)': 8.1,
                    'Viteza maxima (km/h)': 231,
                    'Standard ecologic': "Euro 4",
                    'Raport putere/greutate (CP/tona)': 132.5,
                    'Raport cuplu/greutate (Nm/tona)': 252.4,
                    'Capacitate cilindrica(cc)': 2387,
                    'Putere(hp)': 210,
                    'Cuplu(Nm)': 400,
                    'Codul Motor': "939 A9.000",
                    'Configuratia Motorului': "5 cilindrii in linie, 4 valve per cilindru",
                    'Tipul de asiratie': "Turbosuflanta",
                    'Capacitate baie ulei(l)': 6.4,
                    'Cantitatea lichidului de racire(l)': 7.35,
                    'Masa proprie(kg)': 1585,
                    'Masa maxima autorizata(kg)': 2135,
                    'Volumul minim al portbagajului(l)': 405,
                    'Volumul rezervorului(l)': 70,
                    'Lungime(mm)': 4660,
                    'Latime(mm)': 1828,
                    'Inaltime(mm)': 1417,
                    'Tractiune': "Tracţiune fata",
                    'Tipul cutiei de viteze': "6 trepte, cutie manuală",
                    'Suspensie fata': "Suspensie multi-link independentă",
                    'Suspensie spate': "Suspensie multi-link independentă",
                    'Frane fata': "Discuri ventilate",
                    'Frane spate': "Discuri ventilate",
                    'Emisii(g/km)': 179,
                },
                "3.2 JTS V6 260hp":{
                    imagine:'/alfa159sedan.jpg',
                    'Anii de fabricatie': "2008-2009",
                    'Numarul de scaune': 5,
                    'Numarul de usi': 4,
                    'Consumul urban (l/100km)': 16.4,
                    'Consumul pe autostrada (l/100km)': 7.9,
                    'Consumul mixt (l/100km)': 11,
                    'Tipul Carburantului': "Benzina",
                    'Acceleratie (0-100km/h) (secunde)': 7.1,
                    'Viteza maxima (km/h)': 250,
                    'Standard ecologic': "Euro 4",
                    'Raport putere/greutate (CP/tona)': 168.8,
                    'Raport cuplu/greutate (Nm/tona)': 209.1,
                    'Capacitate cilindrica(cc)': 3195,
                    'Putere(hp)': 260,
                    'Cuplu(Nm)': 322,
                    'Codul Motor': "939 A.000",
                    'Configuratia Motorului': "6 cilindrii in V, 4 valve per cilindru",
                    'Tipul de asiratie': "Aspirat natural",
                    'Capacitate baie ulei(l)': 5.4,
                    'Cantitatea lichidului de racire(l)': 10.3,
                    'Masa proprie(kg)': 1540,
                    'Masa maxima autorizata(kg)': 2090,
                    'Volumul minim al portbagajului(l)': 405,
                    'Volumul rezervorului(l)': 70,
                    'Lungime(mm)': 4660,
                    'Latime(mm)': 1828,
                    'Inaltime(mm)': 1417,
                    'Tractiune': "Tracţiune fata",
                    'Tipul cutiei de viteze': "6 trepte, cutie manuală",
                    'Suspensie fata': "Suspensie multi-link independentă",
                    'Suspensie spate': "Suspensie multi-link independentă",
                    'Frane fata': "Discuri ventilate",
                    'Frane spate': "Disc",
                    'Emisii(g/km)': 260,
                },
            }
        }
    }
}
