export const bazaDateMasini= {
    Bmw: {
        "2005 BMW Seria 3(E9X)": {
            "Sedan 4-door(E90)": {
                "318i 2.0L 129hp": {
                    imagine: '../assets/bmwE90sedan.jpg',
                    'Anii de fabricatie': "2005-2007",
                    'Numarul de scaune':5,
                    'Numarul de usi':4,

                    'Consumul urban(l/100km)':9.5,
                    'Consumul pe autostrada(l/100km)':5.9,
                    'Consumul mixt(l/100km)':7.3,
                    'Tipul Carburantului': "Benzina",
                    'Acceleratie(0-100km/h)(secunde)':10,
                    'Viteza maxima(km/h)':208,
                    'Standard ecologic':"Euro 4",
                    'Raport putere/greutate(CP/tona)':97.4,
                    'Raport cuplu/greutate(Nm/tona)':135.8,

                    'Capacitate cilindrica(cc)': 1991,
                    'Putere(hp)': 129,
                    'Cuplu(Nm)': 180,
                    'Codul Motor': "N46B20B",
                    'Configuratia Motorului': "4 cilindrii in linie, 4 valve per cilindru",
                    'Tipul de asiratie': "Aspirat Natural",
                    'Capacitate baie ulei(l)':4.25,
                    'Cantitatea lichidului de racire(l)':7.2,

                    'Masa proprie(kg)':1325,
                    'Masa maxima autorizata(kg)':1840,
                    'Volumul minim al portbagajului(l)':460,
                    'Volumul rezervorului(l)':60,

                    'Lungime(mm)':4520 ,
                    'Latime(mm)':1817,
                    'Inaltime(mm)':1421,

                    'Tractiune':"Spate",
                    'Tipul cutiei de viteze':"Cutie de viteze manuala - 6 trepte",
                    'Suspensie fata':"Amortizor cu arc",
                    'Suspensie spate':"Arc elicoidal",
                    'Frane fata':"Discuri ventilate",
                    'Frane spate':"Disc",
                },

                "318d 2.0L 122hp": {
                    imagine: '../assets/bmwE90sedan.jpg',
                    "Anii de fabricatie": "2006-2007",
                    'Numarul de scaune': 5,
                    'Numarul de usi': 4,

                    'Consumul urban(l/100km)': 7.6,
                    'Consumul pe autostrada(l/100km)': 4.4,
                    'Consumul mixt(l/100km)': 5.7,
                    'Tipul Carburantului': "Diesel",
                    'Acceleratie(0-100km/h)(secunde)': 10.6,
                    'Viteza maxima(km/h)': 206,
                    'Standard ecologic': "Euro 4",
                    'Raport putere/greutate(CP/tona)': 85,
                    'Raport cuplu/greutate(Nm/tona)': 195.1,

                    'Capacitate cilindrica(cc)': 1995,
                    'Putere(hp)': 122 ,
                    'Cuplu(Nm)': 280,
                    'Codul Motor': "M47D20TU2",
                    'Configuratia Motorului': "4 cilindrii in linie, 4 valve per cilindru",
                    'Tipul de asiratie': "Turbosuflanta",
                    'Capacitate baie ulei(l)': 5.2,
                    'Cantitatea lichidului de racire(l)': 7.8,

                    'Masa proprie(kg)': 1435 ,
                    'Masa maxima autorizata(kg)': 1950 ,
                    'Volumul minim al portbagajului(l)': 460 ,
                    'Volumul rezervorului(l)': 61 ,

                    'Lungime(mm)': 4520,
                    'Latime(mm)': 1817 ,
                    'Inaltime(mm)': 1421 ,

                    'Tractiune': "Spate",
                    'Tipul cutiei de viteze': "Cutie de viteze manuala - 6 trepte",
                    'Suspensie fata': "Independent, tip McPherson cu arcuri elicoidale și bară stabilizatoare",
                    'Suspensie spate': "Arc elicoidal",
                    'Frane fata': "Disc",
                    'Frane spate': "Disc",
                },

                "320d 2.0L 163hp": {
                    imagine: '../assets/bmwE90sedan.jpg',
                    "Anii de fabricatie": "2005-2007",
                    'Numarul de scaune': 5,
                    'Numarul de usi': 4,
                    'Consumul urban(l/100km)': 6.5,
                    'Consumul pe autostrada(l/100km)': 4.5,
                    'Consumul mixt(l/100km)': 5.3,
                    'Tipul Carburantului': "Diesel",
                    'Acceleratie(0-100km/h)(secunde)': 8.3,
                    'Viteza maxima(km/h)': 225,
                    'Standard ecologic': "Euro 4",
                    'Raport putere/greutate(CP/tona)': 113.6,
                    'Raport cuplu/greutate(Nm/tona)': 236.9,
                    'Capacitate cilindrica(cc)': 1995,
                    'Putere(hp)': 163,
                    'Cuplu(Nm)': 340,
                    'Codul Motor': "M47D20TU2",
                    'Configuratia Motorului': "4 cilindrii in linie, 4 valve per cilindru",
                    'Tipul de asiratie': "Turbosuflanta",
                    'Capacitate baie ulei(l)': 5.2,
                    'Cantitatea lichidului de racire(l)': 7.5,
                    'Masa proprie(kg)': 1435,
                    'Masa maxima autorizata(kg)': 1950,
                    'Volumul minim al portbagajului(l)': 460,
                    'Volumul rezervorului(l)': 61,
                    'Lungime(mm)': 4520,
                    'Latime(mm)': 1817,
                    'Inaltime(mm)': 1421,
                    'Tractiune': "Spate",
                    'Tipul cutiei de viteze': "Cutie de viteze manuala - 6 trepte",
                    'Suspensie fata': "Independent, tip McPherson cu arcuri elicoidale și bară stabilizatoare",
                    'Suspensie spate': "Arc elicoidal",
                    'Frane fata': "Disc",
                    'Frane spate': "Disc",
                },

                "320i 2.0L 150hp": {
                    imagine: '../assets/bmwE90sedan.jpg',
                    "Anii de fabricatie": "2005-2007",
                    'Numarul de scaune': 5,
                    'Numarul de usi': 4,
                    'Consumul urban(l/100km)': 10.7,
                    'Consumul pe autostrada(l/100km)': 5.6,
                    'Consumul mixt(l/100km)': 7.4,
                    'Tipul Carburantului': "Benzina",
                    'Acceleratie(0-100km/h)(secunde)': 8.5,
                    'Viteza maxima(km/h)': 220,
                    'Standard ecologic': "Euro 4",
                    'Raport putere/greutate(CP/tona)': 107.5,
                    'Raport cuplu/greutate(Nm/tona)': 143.4,
                    'Capacitate cilindrica(cc)': 1995,
                    'Putere(hp)': 150,
                    'Cuplu(Nm)': 200,
                    'Codul Motor': "N46B20B",
                    'Configuratia Motorului': "4 cilindrii in linie, 4 valve per cilindru",
                    'Tipul de asiratie': "Aspirat Natural",
                    'Capacitate baie ulei(l)': 4.25,
                    'Cantitatea lichidului de racire(l)': 7.2,
                    'Masa proprie(kg)': 1395,
                    'Masa maxima autorizata(kg)': 1840,
                    'Volumul minim al portbagajului(l)': 460,
                    'Volumul rezervorului(l)': 60,
                    'Lungime(mm)': 4520,
                    'Latime(mm)': 1817,
                    'Inaltime(mm)': 1421,
                    'Tractiune': "Spate",
                    'Tipul cutiei de viteze': "Cutie de viteze manuala - 6 trepte",
                    'Suspensie fata': "Amortizor cu arc",
                    'Suspensie spate': "Arc elicoidal",
                    'Frane fata': "Discuri ventilate",
                    'Frane spate': "Disc",
                },


                "325d 3.0L 197hp": {
                    imagine: '../assets/bmwE90sedan.jpg',
                    "Anii de fabricatie": "2006-2008",
                    'Numarul de scaune': 5,
                    'Numarul de usi': 4,
                    'Consumul urban(l/100km)': 8.6,
                    'Consumul pe autostrada(l/100km)': 5.1,
                    'Consumul mixt(l/100km)': 6.4,
                    'Tipul Carburantului': "Diesel",
                    'Acceleratie(0-100km/h)(secunde)': 7.4,
                    'Viteza maxima(km/h)': 235,
                    'Standard ecologic': "Euro 4",
                    'Raport putere/greutate(CP/tona)': 131.3,
                    'Raport cuplu/greutate(Nm/tona)': 266.7,
                    'Capacitate cilindrica(cc)': 2993,
                    'Putere(hp)': 197,
                    'Cuplu(Nm)': 400,
                    'Codul Motor': "M57D30TU2",
                    'Configuratia Motorului': "6 cilindrii in linie, 4 valve per cilindru",
                    'Tipul de asiratie': "Turbosuflanta",
                    'Capacitate baie ulei(l)': 7.5,
                    'Cantitatea lichidului de racire(l)': 7.9,
                    'Masa proprie(kg)': 1500,
                    'Masa maxima autorizata(kg)': 2045,
                    'Volumul minim al portbagajului(l)': 460,
                    'Volumul rezervorului(l)': 61,
                    'Lungime(mm)': 4520,
                    'Latime(mm)': 1820,
                    'Inaltime(mm)': 1420,
                    'Tractiune': "Spate",
                    'Tipul cutiei de viteze': "Cutie de viteze manuala - 6 trepte",
                    'Suspensie fata': "Independent de tip McPherson",
                    'Suspensie spate': "Suspensie multi-link independentă",
                    'Frane fata': "Discuri ventilate",
                    'Frane spate': "Disc",
                },

                "325i 2.5L 218hp": {
                    imagine: '../assets/bmwE90sedan.jpg',
                    "Anii de fabricatie": "2005-2007",
                    'Numarul de scaune': 5,
                    'Numarul de usi': 4,
                    'Consumul urban(l/100km)': 12.1,
                    'Consumul pe autostrada(l/100km)': 6.2,
                    'Consumul mixt(l/100km)': 8.4,
                    'Tipul Carburantului': "Benzina",
                    'Acceleratie(0-100km/h)(secunde)': 7,
                    'Viteza maxima(km/h)': 245,
                    'Standard ecologic': "Euro 4",
                    'Raport putere/greutate(CP/tona)': 146.3,
                    'Raport cuplu/greutate(Nm/tona)': 167.8,
                    'Capacitate cilindrica(cc)': 2497,
                    'Putere(hp)': 218,
                    'Cuplu(Nm)': 250,
                    'Codul Motor': "N52B25A",
                    'Configuratia Motorului': "6 cilindrii in linie, 4 valve per cilindru",
                    'Tipul de asiratie': "Aspirat Natural",
                    'Capacitate baie ulei(l)': 6.5,
                    'Cantitatea lichidului de racire(l)': 8.2,
                    'Masa proprie(kg)': 1490,
                    'Masa maxima autorizata(kg)': 1935,
                    'Volumul minim al portbagajului(l)': 460,
                    'Volumul rezervorului(l)': 60,
                    'Lungime(mm)': 4520,
                    'Latime(mm)': 1820,
                    'Inaltime(mm)': 1420,
                    'Tractiune': "Spate",
                    'Tipul cutiei de viteze': "Cutie de viteze manuala - 6 trepte",
                    'Suspensie fata': "Amortizor cu arc",
                    'Suspensie spate': "Arc elicoidal",
                    'Frane fata': "Discuri ventilate",
                    'Frane spate': "Disc",
                },



                "330i 3.0L 258hp": {
                    imagine: '../assets/bmwE90sedan.jpg',
                    "Anii de fabricatie": "2005-2007",
                    'Numarul de scaune': 5,
                    'Numarul de usi': 4,
                    'Consumul urban(l/100km)': 12.7,
                    'Consumul pe autostrada(l/100km)': 6.4,
                    'Consumul mixt(l/100km)': 8.7,
                    'Tipul Carburantului': "Benzina",
                    'Acceleratie(0-100km/h)(secunde)': 6.3,
                    'Viteza maxima(km/h)': 250,
                    'Standard ecologic': "Euro 4",
                    'Raport putere/greutate(CP/tona)': 169.2,
                    'Raport cuplu/greutate(Nm/tona)': 196.7,
                    'Capacitate cilindrica(cc)': 2996,
                    'Putere(hp)': 258,
                    'Cuplu(Nm)': 300,
                    'Codul Motor': "N52B30A",
                    'Configuratia Motorului': "6 cilindrii in linie, 4 valve per cilindru",
                    'Tipul de asiratie': "Aspirat Natural",
                    'Capacitate baie ulei(l)': 6.5,
                    'Cantitatea lichidului de racire(l)': 8.2,
                    'Masa proprie(kg)': 1525,
                    'Masa maxima autorizata(kg)': 1970,
                    'Volumul minim al portbagajului(l)': 460,
                    'Volumul rezervorului(l)': 60,
                    'Lungime(mm)': 4520,
                    'Latime(mm)': 1820,
                    'Inaltime(mm)': 1420,
                    'Tractiune': "Spate",
                    'Tipul cutiei de viteze': "Cutie de viteze manuala - 6 trepte",
                    'Suspensie fata': "Amortizor cu arc",
                    'Suspensie spate': "Arc elicoidal",
                    'Frane fata': "Discuri ventilate",
                    'Frane spate': "Disc",
                },

                "330d 3.0L 231hp": {
                    imagine: '../assets/bmwE90sedan.jpg',
                    "Anii de fabricatie": "2005-2007",
                    'Numarul de scaune': 5,
                    'Numarul de usi': 4,
                    'Consumul urban(l/100km)': 8.8,
                    'Consumul pe autostrada(l/100km)': 5.2,
                    'Consumul mixt(l/100km)': 6.6,
                    'Tipul Carburantului': "Diesel",
                    'Acceleratie(0-100km/h)(secunde)': 6.7,
                    'Viteza maxima(km/h)': 250,
                    'Standard ecologic': "Euro 4",
                    'Raport putere/greutate(CP/tona)': 152.5,
                    'Raport cuplu/greutate(Nm/tona)': 330,
                    'Capacitate cilindrica(cc)': 2993,
                    'Putere(hp)': 231,
                    'Cuplu(Nm)': 500,
                    'Codul Motor': "M57D30TU2",
                    'Configuratia Motorului': "6 cilindrii in linie, 4 valve per cilindru",
                    'Tipul de asiratie': "Aspirat Natural",
                    'Capacitate baie ulei(l)': 7.5,
                    'Cantitatea lichidului de racire(l)': 7.8,
                    'Masa proprie(kg)': 1515,
                    'Masa maxima autorizata(kg)': 2030,
                    'Volumul minim al portbagajului(l)': 460,
                    'Volumul rezervorului(l)': 61,
                    'Lungime(mm)': 4520,
                    'Latime(mm)': 1820,
                    'Inaltime(mm)': 1420,
                    'Tractiune': "Spate",
                    'Tipul cutiei de viteze': "Cutie de viteze manuala - 6 trepte",
                    'Suspensie fata': "Amortizor cu arc",
                    'Suspensie spate': "Arc elicoidal",
                    'Frane fata': "Discuri ventilate",
                    'Frane spate': "Disc",
                },


            },
        },
    },

    Audi: {
        "2007 Audi A4(B8)":{
            "Sedan 4-door":{
                "1.8 TFSI 120hp": {
                    imagine: '../assets/audia4b8sedan.jpg',
                    "Anii de fabricatie": "2007-2011",
                    'Numarul de scaune': 5,
                    'Numarul de usi': 4,
                    'Consumul urban(l/100km)': 9.9,
                    'Consumul pe autostrada(l/100km)': 5.5,
                    'Consumul mixt(l/100km)': 7.1,
                    'Tipul Carburantului': "Benzina",
                    'Acceleratie(0-100km/h)(secunde)': 10.5,
                    'Viteza maxima(km/h)': 208,
                    'Standard ecologic': "Euro 4",
                    'Raport putere/greutate(CP/tona)': 85.1,
                    'Raport cuplu/greutate(Nm/tona)': 163.1,
                    'Capacitate cilindrica(cc)': 1798,
                    'Putere(hp)': 120,
                    'Cuplu(Nm)': 230,
                    'Codul Motor': "EA888 / CDHA",
                    'Configuratia Motorului': "4 cilindrii in linie, 4 valve per cilindru",
                    'Tipul de asiratie': "Turbosuflanta",
                    'Capacitate baie ulei(l)': 4.6,
                    'Cantitatea lichidului de racire(l)': 7,
                    'Masa proprie(kg)': 1410,
                    'Masa maxima autorizata(kg)': 1960,
                    'Volumul minim al portbagajului(l)': 480,
                    'Volumul rezervorului(l)': 65,
                    'Lungime(mm)': 4703,
                    'Latime(mm)': 1826,
                    'Inaltime(mm)': 1427,
                    'Tractiune': "Fata",
                    'Tipul cutiei de viteze': "Cutie de viteze manuala - 6 trepte",
                    'Suspensie fata': "Suspensie multi-link independentă",
                    'Suspensie spate': "Suspensie independentă cu arc multi-legături cu stabilizator",
                    'Frane fata': "Discuri ventilate",
                    'Frane spate': "Disc",
                    'Emisii(g/km)':  169 ,
                },

                "1.8 TFSI 160hp": {
                    imagine: '../assets/audia4b8sedan.jpg',
                    'Anii de fabricatie': "2007-2011",
                    'Numarul de scaune': 5,
                    'Numarul de usi': 4,
                    'Consumul urban(l/100km)': 9.9,
                    'Consumul pe autostrada(l/100km)': 5.5,
                    'Consumul mixt(l/100km)': 7.1,
                    'Tipul Carburantului': "Benzina",
                    'Acceleratie(0-100km/h)(secunde)': 8.6,
                    'Viteza maxima(km/h)': 225,
                    'Standard ecologic': "Euro 4",
                    'Raport putere/greutate(CP/tona)': 113.5,
                    'Raport cuplu/greutate(Nm/tona)': 177.3,
                    'Capacitate cilindrica(cc)': 1798,
                    'Putere(hp)': 160,
                    'Cuplu(Nm)': 250,
                    'Codul Motor': "EA888 / CDHB",
                    'Configuratia Motorului': "4 cilindrii in linie, 4 valve per cilindru",
                    'Tipul de asiratie': "Turbosuflanta",
                    'Capacitate baie ulei(l)': 4.6,
                    'Cantitatea lichidului de racire(l)': 7,
                    'Masa proprie(kg)': 1410,
                    'Masa maxima autorizata(kg)': 1960,
                    'Volumul minim al portbagajului(l)': 480,
                    'Volumul rezervorului(l)': 65,
                    'Lungime(mm)': 4703,
                    'Latime(mm)': 1826,
                    'Inaltime(mm)': 1427,
                    'Tractiune': "Fata",
                    'Tipul cutiei de viteze': "Cutie de viteze manuala - 6 trepte",
                    'Suspensie fata': "Suspensie multi-link independentă",
                    'Suspensie spate': "Suspensie independentă cu arc multi-legături cu stabilizator",
                    'Frane fata': "Discuri ventilate",
                    'Frane spate': "Disc",
                    'Emisii(g/km)':  169 ,
                },


                "2.0 TDI 143hp": {
                    imagine: '../assets/audia4b8sedan.jpg',
                    'Anii de fabricatie': "2007-2011",
                    'Numarul de scaune': 5,
                    'Numarul de usi': 4,
                    'Consumul urban(l/100km)': 7.5,
                    'Consumul pe autostrada(l/100km)': 4.3,
                    'Consumul mixt(l/100km)': 5.5,
                    'Tipul Carburantului': "Diesel",
                    'Acceleratie(0-100km/h)(secunde)': 9.4,
                    'Viteza maxima(km/h)': 215,
                    'Standard ecologic': "Euro 4",
                    'Raport putere/greutate(CP/tona)': 97.9,
                    'Raport cuplu/greutate(Nm/tona)': 219.2,
                    'Capacitate cilindrica(cc)': 1968,
                    'Putere(hp)': 143,
                    'Cuplu(Nm)': 320,
                    'Codul Motor': "EA189 / CAGA",
                    'Configuratia Motorului': "4 cilindrii in linie, 4 valve per cilindru",
                    'Tipul de asiratie': "Turbosuflanta",
                    'Capacitate baie ulei(l)': 5,
                    'Cantitatea lichidului de racire(l)': 7.5,
                    'Masa proprie(kg)': 1460,
                    'Masa maxima autorizata(kg)': 2010,
                    'Volumul minim al portbagajului(l)': 480,
                    'Volumul rezervorului(l)': 70,
                    'Lungime(mm)': 4703,
                    'Latime(mm)': 1826,
                    'Inaltime(mm)': 1427,
                    'Tractiune': "Fata",
                    'Tipul cutiei de viteze': "Cutie de viteze manuala - 6 trepte",
                    'Suspensie fata': "Suspensie multi-link independentă",
                    'Suspensie spate': "Suspensie independentă cu arc multi-legături cu stabilizator",
                    'Frane fata': "Discuri ventilate",
                    'Frane spate': "Disc",
                    'Emisii(g/km)':  144 ,
                },

                "2.0 TDI 170hp": {
                    imagine: '../assets/audia4b8sedan.jpg',
                    'Anii de fabricatie': "2007-2011",
                    'Numarul de scaune': 5,
                    'Numarul de usi': 4,
                    'Consumul urban(l/100km)': 6.2,
                    'Consumul pe autostrada(l/100km)': 4.4,
                    'Consumul mixt(l/100km)': 5.1,
                    'Tipul Carburantului': "Diesel",
                    'Acceleratie(0-100km/h)(secunde)': 8.4,
                    'Viteza maxima(km/h)': 230,
                    'Standard ecologic': "Euro 5",
                    'Raport putere/greutate(CP/tona)': 116,
                    'Raport cuplu/greutate(Nm/tona)': 238.9,
                    'Capacitate cilindrica(cc)': 1968,
                    'Putere(hp)': 170,
                    'Cuplu(Nm)': 350,
                    'Codul Motor': "EA189 / CAHA",
                    'Configuratia Motorului': "4 cilindrii in linie, 4 valve per cilindru",
                    'Tipul de asiratie': "Turbosuflanta",
                    'Capacitate baie ulei(l)': 5,
                    'Masa maxima autorizata(kg)': 2015,
                    'Volumul minim al portbagajului(l)': 480,
                    'Volumul rezervorului(l)': 65,
                    'Lungime(mm)': 4703,
                    'Latime(mm)': 1826,
                    'Inaltime(mm)': 1427,
                    'Tractiune': "Fata",
                    'Tipul cutiei de viteze': "Cutie de viteze manuala - 6 trepte",
                    'Suspensie fata': "Suspensie multi-link independentă",
                    'Suspensie spate': "Suspensie independentă cu arc multi-legături cu stabilizator",
                    'Frane fata': "Discuri ventilate",
                    'Frane spate': "Disc",
                    'Emisii(g/km)':  134 ,
                },



                "2.0 TFSI 180hp": {
                    imagine: '../assets/audia4b8sedan.jpg',
                    'Anii de fabricatie': "2007-2011",
                    'Numarul de scaune': 5,
                    'Numarul de usi': 4,
                    'Consumul urban(l/100km)': 9,
                    'Consumul pe autostrada(l/100km)': 5.2,
                    'Consumul mixt(l/100km)': 6.6,
                    'Tipul Carburantului': "Benzina",
                    'Acceleratie(0-100km/h)(secunde)': 7.9,
                    'Viteza maxima(km/h)': 236,
                    'Standard ecologic': "Euro 5",
                    'Raport putere/greutate(CP/tona)': 125.9,
                    'Raport cuplu/greutate(Nm/tona)': 223.8,
                    'Capacitate cilindrica(cc)': 1984,
                    'Putere(hp)': 180,
                    'Cuplu(Nm)': 320,
                    'Codul Motor': "EA888 / CDNB",
                    'Configuratia Motorului': "4 cilindrii in linie, 4 valve per cilindru",
                    'Tipul de asiratie': "Turbosuflanta",
                    'Capacitate baie ulei(l)': 4.6,
                    'Cantitatea lichidului de racire(l)': 7,
                    'Masa proprie(kg)': 1430,
                    'Masa maxima autorizata(kg)': 1980,
                    'Volumul minim al portbagajului(l)': 480,
                    'Volumul rezervorului(l)': 65,
                    'Lungime(mm)': 4703,
                    'Latime(mm)': 1826,
                    'Inaltime(mm)': 1427,
                    'Tractiune': "Fata",
                    'Tipul cutiei de viteze': "Cutie de viteze manuala - 6 trepte",
                    'Suspensie fata': "Suspensie multi-link independentă",
                    'Suspensie spate': "Suspensie independentă cu arc multi-legături cu stabilizator",
                    'Frane fata': "Discuri ventilate",
                    'Frane spate': "Disc",
                    'Emisii(g/km)': 154,
                },

                "2.0 TFSI 211hp": {
                    imagine: '../assets/audia4b8sedan.jpg',
                    'Anii de fabricatie': "2007-2011",
                    'Numarul de scaune': 5,
                    'Numarul de usi': 4,
                    'Consumul urban(l/100km)': 9,
                    'Consumul pe autostrada(l/100km)': 5.2,
                    'Consumul mixt(l/100km)': 6.6,
                    'Tipul Carburantului': "Benzina",
                    'Acceleratie(0-100km/h)(secunde)': 6.9,
                    'Viteza maxima(km/h)': 250,
                    'Standard ecologic': "Euro 5",
                    'Raport putere/greutate(CP/tona)': 147,
                    'Raport cuplu/greutate(Nm/tona)': 243.9,
                    'Capacitate cilindrica(cc)': 1984,
                    'Putere(hp)': 211,
                    'Cuplu(Nm)': 350,
                    'Codul Motor': "EA888 / CAEB",
                    'Configuratia Motorului': "4 cilindrii in linie, 4 valve per cilindru",
                    'Tipul de asiratie': "Turbosuflanta",
                    'Capacitate baie ulei(l)': 4.6,
                    'Cantitatea lichidului de racire(l)': 7,
                    'Masa proprie(kg)': 1435,
                    'Masa maxima autorizata(kg)': 1985,
                    'Volumul minim al portbagajului(l)': 480,
                    'Volumul rezervorului(l)': 65,
                    'Lungime(mm)': 4703,
                    'Latime(mm)': 1826,
                    'Inaltime(mm)': 1427,
                    'Tractiune': "Fata",
                    'Tipul cutiei de viteze': "Cutie de viteze manuala - 6 trepte",
                    'Suspensie fata': "Suspensie multi-link independentă",
                    'Suspensie spate': "Suspensie independentă cu arc multi-legături cu stabilizator",
                    'Frane fata': "Discuri ventilate",
                    'Frane spate': "Disc",
                    'Emisii(g/km)': 154 ,
                },

                "2.7 TDI V6 190hp": {
                    imagine: '../assets/audia4b8sedan.jpg',
                    'Anii de fabricatie': "2007-2011",
                    'Numarul de scaune': 5,
                    'Numarul de usi': 4,
                    'Consumul urban(l/100km)': 9,
                    'Consumul pe autostrada(l/100km)': 5.2,
                    'Consumul mixt(l/100km)': 6.6,
                    'Tipul Carburantului': "Diesel",
                    'Acceleratie(0-100km/h)(secunde)': 8.2,
                    'Viteza maxima(km/h)': 230,
                    'Standard ecologic': "Euro 5",
                    'Raport putere/greutate(CP/tona)': 121,
                    'Raport cuplu/greutate(Nm/tona)': 254.8,
                    'Capacitate cilindrica(cc)': 2697,
                    'Putere(hp)': 190,
                    'Cuplu(Nm)': 400,
                    'Codul Motor': "EA896 / CGKA",
                    'Configuratia Motorului': "6 cilindrii in V, 4 valve per cilindru",
                    'Tipul de asiratie': "Turbosuflanta",
                    'Capacitate baie ulei(l)': 6.9,
                    'Cantitatea lichidului de racire(l)': 12,
                    'Masa proprie(kg)': 1600,
                    'Masa maxima autorizata(kg)': 2120,
                    'Volumul minim al portbagajului(l)': 480,
                    'Volumul rezervorului(l)': 65,
                    'Lungime(mm)': 4703,
                    'Latime(mm)': 1826,
                    'Inaltime(mm)': 1427,
                    'Tractiune': "Fata",
                    'Tipul cutiei de viteze': "Cutie de viteze manuala - 6 trepte",
                    'Suspensie fata': "Suspensie multi-link independentă",
                    'Suspensie spate': "Suspensie independentă cu arc multi-legături cu stabilizator",
                    'Frane fata': "Discuri ventilate",
                    'Frane spate': "Disc",
                    'Emisii(g/km)': 159 ,
                },


                "3.0 TDI quattro 240hp": {
                    imagine: '../assets/audia4b8sedan.jpg',
                    'Anii de fabricatie': "2007-2011",
                    'Numarul de scaune': 5,
                    'Numarul de usi': 4,
                    'Consumul urban(l/100km)': 9.6,
                    'Consumul pe autostrada(l/100km)': 5.4,
                    'Consumul mixt(l/100km)': 6.9,
                    'Tipul Carburantului': "Diesel",
                    'Acceleratie(0-100km/h)(secunde)': 6.1,
                    'Viteza maxima(km/h)': 250,
                    'Standard ecologic': "Euro 4",
                    'Raport putere/greutate(CP/tona)': 145,
                    'Raport cuplu/greutate(Nm/tona)': 302.1,
                    'Capacitate cilindrica(cc)': 2967,
                    'Putere(hp)': 240,
                    'Cuplu(Nm)': 500,
                    'Codul Motor': "EA896 / CCWA",
                    'Configuratia Motorului': "6 cilindrii in V, 4 valve per cilindru",
                    'Tipul de asiratie': "Turbosuflanta",
                    'Capacitate baie ulei(l)': 6.9,
                    'Cantitatea lichidului de racire(l)': 9,
                    'Masa proprie(kg)': 1655,
                    'Masa maxima autorizata(kg)': 2205,
                    'Volumul minim al portbagajului(l)': 480,
                    'Volumul rezervorului(l)': 65,
                    'Lungime(mm)': 4703,
                    'Latime(mm)': 1826,
                    'Inaltime(mm)': 1427,
                    'Tractiune': "Tractiune Integrala(4x4)",
                    'Tipul cutiei de viteze': "Cutie de viteze manuala - 6 trepte",
                    'Suspensie fata': "Suspensie multi-link independentă",
                    'Suspensie spate': "Suspensie independentă cu arc multi-legături cu stabilizator",
                    'Frane fata': "Discuri ventilate",
                    'Frane spate': "Disc",
                    'Emisii(g/km)': 183 ,
                },

                "3.2 FSI quattro 265hp": {
                    imagine: '../assets/audia4b8sedan.jpg',
                    'Anii de fabricatie': "2007-2011",
                    'Numarul de scaune': 5,
                    'Numarul de usi': 4,
                    'Consumul urban(l/100km)': 13,
                    'Consumul pe autostrada(l/100km)': 6.6,
                    'Consumul mixt(l/100km)': 8.9,
                    'Tipul Carburantului': "Benzina",
                    'Acceleratie(0-100km/h)(secunde)': 6.2,
                    'Viteza maxima(km/h)': 250,
                    'Standard ecologic': "Euro 4",
                    'Raport putere/greutate(CP/tona)': 167.7,
                    'Raport cuplu/greutate(Nm/tona)': 208.9,
                    'Capacitate cilindrica(cc)': 3197,
                    'Putere(hp)': 265,
                    'Cuplu(Nm)': 330,
                    'Codul Motor': "EA390 / CALA",
                    'Configuratia Motorului': "6 cilindrii in V, 4 valve per cilindru",
                    'Tipul de asiratie': "Turbosuflanta",
                    'Capacitate baie ulei(l)': 6.2,
                    'Cantitatea lichidului de racire(l)': 9,
                    'Masa proprie(kg)': 1580,
                    'Masa maxima autorizata(kg)': 2130,
                    'Volumul minim al portbagajului(l)': 480,
                    'Volumul rezervorului(l)': 64,
                    'Lungime(mm)': 4703,
                    'Latime(mm)': 1826,
                    'Inaltime(mm)': 1427,
                    'Tractiune': "Tractiune Integrala(4x4)",
                    'Tipul cutiei de viteze': "Cutie de viteze manuala - 6 trepte",
                    'Suspensie fata': "Suspensie multi-link independentă",
                    'Suspensie spate': "Suspensie independentă cu arc multi-legături cu stabilizator",
                    'Frane fata': "Discuri ventilate",
                    'Frane spate': "Disc",
                    'Emisii(g/km)': 213 ,
                },


            },
        },
    },
}
